- belar/metrics/__init__.py
- belar/metrics/factual.py
- belar/utils.py
- tests/benchmarks/benchmark.py
- Fix score inconsistency caused due to attention mask
fixes : #17
> Fix Entailment score

- README.md
Instead of `When it comes to RAG pipelines`, it was written `When is comes to RAG pipelines`. 
Rectified ✅
> Hotfix: Update Readme [ SpellingError ]

- experiments/assesments/metrics_assesments.ipynb
- src/ragas/metrics/context_relevance.py
Added support for new context relevancy metrics
The earlier used context_relevancy metric was found to have a poor correlation with actual results. 
New paradigm leverages candidate sentence extraction with self-consistency checks to ensure far better results even with larger context lengths.
> Context Relevancy v2

- README.md
- docs/metrics.md
- experiments/assesments/metrics_assesments.ipynb
- src/ragas/metrics/answer_relevance.py
Added a new answer relevancy method that can use any LLM
The earlier method was using the t5 model which was giving poor results with issues like multilingualism. The process was also slow due to the local model.
Introduced a new paradigm that uses a combination of question generation and self-consistency.
> New Answer relevancy metrics

- src/ragas/metrics/faithfulnes.py
Fixes #80 
Improved NLI prompt in faithfulness metrics
The earlier NLI prompt was deviating from the specified format.
Changed prompt format and made instructions more clear.
> added improved  NLI prompt

- src/ragas/metrics/context_relevance.py
Improve context relevancy prompt 
LLM has trouble doing candidate sentence extraction. The current prompt has caused issues where context relevancy becomes zero due to a suboptimal prompt. This prompt is tested on data from Arxiv, StackOverflow, etc. 
fixes: #109
> Improve context relevancy

- src/ragas/validation.py
- tests/unit/test_validation.py
When I try to do the following, I got error:
```python
ds = Dataset.from_dict(
{
"question": ["question"],
"answer": ["answer"],
"contexts": [["context"]],
}
)
from ragas import evaluate
from ragas.metrics import Faithfulness
evaluate(dataset =ds, metrics=[Faithfulness(batch_size=1)])
```
```
KeyError: "Column ground_truths not in the dataset. Current columns in the dataset: ['question', 'answer', 'contexts']"
```
But `ground_truths ` is not needed for `Faithfulness` .
This PR is to fix it.
> Fix remap_column_names 

- docs/quickstart.ipynb
To reduce some confusion, add a note mentioning that ground truth labels are only required for context_recall, since the tool can generate other metrics in a "ground truth" free manner.
> Add note about when ground truth labels are required

- src/ragas/metrics/answer_relevance.py
> bug fix: embeddings -> embedding

- src/ragas/metrics/context_relevance.py
Changed: python3.9/site-packages/ragas/metrics/context_relevance.py", line 162, in _score_batch
From: `score = min(len(indices) / len(context_sents), 1)`
To: ``` if len(context_sents) == 0:
score = 0
else:
score = min(len(indices) / len(context_sents), 1)```
fixes: #153
> ZeroDivisionError in context_relevance

- src/ragas/metrics/context_precision.py
I'm not sure when `0.1.0` is scheduled for release, but in the meantime, when `context_precision` is (correctly) called, you still get a deprecation warning because of what I _think_ is a typo.
Before change:
After change:
> don't warn when `context_precision` is correctly called

- docs/getstarted/evaluation.md
Updating some minor typos (outlined in #192).
> Fix typos in Eval doc

- src/ragas/testset/testset_generator.py
- src/ragas/testset/utils.py
Usage
```py
from langchain.document_loaders import PubMedLoader
from ragas.testset import TestsetGenerator
loader = PubMedLoader("liver", load_max_docs=10)
docs = loader.load()
len(docs)
testsetgenerator = TestsetGenerator.from_default()
test_size = 10
testset = testsetgenerator.generate(docs, test_size=test_size)
test_df = testset.to_pandas()
test_df.head()
```
> feat: langchain documents support for TestsetGenerator

- docs/concepts/testset_generation.md
- docs/howtos/integrations/langchain.ipynb
Custom LLMs did not work for customized test set generation without first casting LLMs to RagasLLM
> fix: Add RagasLLM for customized test set generation

- src/ragas/llms/base.py
added support for llm, chat and embeddings
```py
from langchain.llms import VertexAI
from langchain.chat_models import ChatVertexAI
from ragas.llms import LangchainLLM
from ragas.metrics import faithfulness
llm = VertexAI(credentials=creds)
chat = ChatVertexAI(credentials=creds)
ragas_llm = LangchainLLM(llm)
faithfulness.llm = ragas_llm
```
if your looking to change the embeddings as well
```py
from langchain.embeddings import VertexAIEmbeddings
from ragas.metrics import AnswerRelevancy
embeddings = VertexAIEmbeddings(credentials=creds)
ar = AnswerRelevancy(embeddings=embeddings)
r = evaluate(fiqa_eval.select(range(3)), metrics=[ar])
```
> fix: added support for google vertexAI

- src/ragas/embeddings/base.py
- src/ragas/metrics/_answer_similarity.py
When passing the embeddings for example in the answer relevancy, sentence transformers do not pass assert isinstance(embeddings, Tensor) in src/ragas/embeddings/base.py, so the solution is to add "convert_to_tensor": True as follows:
AnswerRelevancy(embeddings=HuggingfaceEmbeddings(
model_name='intfloat/multilingual-e5-large', encode_kwargs={"convert_to_tensor": True}))
However, this does not work for the src/ragas/metrics/_answer_similarity.py because encode_kwargs are initialized with self.embeddings.encode_kwargs = {"batch_size": self.batch_size}
my proposed solution is to change line 56 to:
self.embeddings.encode_kwargs = {"batch_size": self.batch_size, "convert_to_tensor": True}
> Custom embeddings from HuggingFace (sentence transformer) do not pass the assertion in src/ragas/metrics/_answer_similarity.py  

- src/ragas/testset/testset_generator.py
* Changed context from str to List[str] so that it is consistent with eval. Now output of TestDataset can be used for evaluation.
*  Changed typo in _generate_doc_nodes_map
*  Changed TestDataset class to reflect the changes in test set generation. Drawback is episode_done will be True in all cases as data is changed at the level above.
> Make testgenerator output compatible with evaluate

- docs/howtos/customisations/azure-openai.ipynb
The code previously raised a NotFoundError due to an incorrect reference to the OpenAIEmbeddings class. This commit corrects the reference to AzureOpenAIEmbeddings, resolving the error. #326
> Fix OpenAIEmbeddings reference error in answer_relevancy

- src/ragas/metrics/base.py
Add a conditional statement to check whether `validate_api_key` exists for the ChatModel Object from Langchain #348
> fix: bedrock llm error when evaluating rag qa `validate_api_key`

- src/ragas/llms/langchain.py
- src/ragas/metrics/_answer_relevance.py
Closed other PR.
1. Merge with latest changes
2. Added integration with Amazon API Gateway
3. fixed bug in _answer_relevance.py, caused by text empty or NaN in the cosine_sim calculation
> Added integration with Amazon API Gateway + bug fix in _answer_relevance.py

- requirements/dev.txt
- src/ragas/metrics/_context_recall.py
Maybe this isssue https://github.com/explodinggradients/ragas/issues/352 is talking about the same thing.
> fix(metrics): avoid getting none in context_recall

- src/ragas/async_utils.py
- src/ragas/testset/testset_generator.py
I am using Azure OpenAI API to generate testset. However, Azure's API is sensitive to content and can easily trigger the following returns:
```python
{'id': 'fake_id', 'choices': [{'finish_reason': 'content_filter', 'index': 0, 'message': {'content
': None, 'role': 'assistant', 'function_call': None, 'tool_calls': None}}], 'created': 1702175894, 'model': 'gpt-4-32k', 'object'
: 'chat.completion', 'system_fingerprint': None, 'usage': {'completion_tokens': 21, 'prompt_tokens': 4271, 'total_tokens': 4292}}
```
The `finish_reason` is `content_filter` and the content is `None`.
When conducting [`create_llm_result()`](https://github.com/explodinggradients/ragas/blob/main/src/ragas/llms/openai.py#L134), because the content is `None`, an error will be raised.
```python
Error occurred: ('Fatal …
```
> feat(testset_generator): support error catching in generation process

- src/ragas/metrics/_context_precision.py
- src/ragas/metrics/_context_recall.py
- src/ragas/metrics/_faithfulness.py
this commit changes the verdict system in our natural language inference module from 'Yes/No' to a binary '1/0' format. This modification aims to streamline decision-making and ensure consistency across various languages, enhancing the system's efficiency and reliability in multilingual contexts
> Updated NLI Verdicts to Binary Format

- docs/howtos/customisations/embeddings.ipynb
- docs/howtos/customisations/index.md
* added docs for ragas embeddings
> added docs for ragas embeddings

- docs/_static/js/mendable_chat_bubble.js
- docs/conf.py
Hey team,
We've been thoroughly enjoying Ragas. We stumbled upon you guys after the OpenAI talk and we’ve been super impressed. Here at Mendable, we use RAG pipelines all over so this has been super helpful!
Recently, when trying to implement, we stumbled into some questions. So, we ended up ingesting the Ragas docs into Mendable.ai and started using it to answer some of the questions that we had about the product.
We thought it did an awesome job answering most of them, so we figured to PR and offer it as a feature for your docs. We implemented a small button on the screen's bottom right which unveils an AI-powered chat interface when clicked. There, users can ask questions about Ragas' documentation and even debug code. The bot will learn with the documentation daily so it will be …
> docs: AI copilot implementation

- docs/howtos/customisations/llms.ipynb
Improvements in punctuation and readability of the document
> Small improvements to documentation custom LLMs

- src/ragas/metrics/_answer_correctness.py
- src/ragas/metrics/_context_precision.py
- src/ragas/metrics/_context_recall.py
- src/ragas/metrics/_faithfulness.py
- src/ragas/metrics/critique.py
Here is the running time of answer correctness. It's clear that the json loading process takes too much time.
The long json loading time indicates the model always outputs wrong json format. But it's strange since I am using GPT4 and the model should be clever enough to produce json output.
So I checked the model output and found the the model was misleading by the prompt examples.
Before this fix, the examples were all strings. When using the `json.dumps()` in the `prompt.format()`, the output would be like 
``` python
Extracted statements: "{{\n                \"statements that are present in both the answer and the ground truth\": [\"The sun's primary function is to provide light\"],\n                \"statements present in the answer but not found in the ground truth\": [\"The sun is …
```
> fix(metrics): wrong usage of prompt

- src/ragas/evaluation.py
- src/ragas/executor.py
- src/ragas/llms/json_load.py
- src/ragas/llms/prompt.py
- src/ragas/metrics/_answer_correctness.py
- src/ragas/metrics/_answer_relevance.py
- src/ragas/metrics/_context_precision.py
- src/ragas/metrics/_context_recall.py
- src/ragas/metrics/_context_relevancy.py
- src/ragas/metrics/_faithfulness.py
- src/ragas/metrics/critique.py
- tests/benchmarks/benchmark_eval.py
- added async version for `json_load.asafe_load`
- ported all metrics
note: in order to get optimal async operation we need to support async embeddings too. will make a followup PR for that
> feat: added async version for `json_load` 

- src/ragas/metrics/_context_recall.py
Simple workaround to fix `AttributeError: 'str' object has no attribute 'get'` caused by non consistent LLM evaluation output. Resulting in the use of .get() on a str instead of a dict.  
More on this [issue ](https://github.com/explodinggradients/ragas/issues/429)
> Fix: context_recall AttributeError

- docs/concepts/metrics/index.md
Fixing a typo of "faithfulness" in the docs (extra 's')
> Fixing typo in faithfulness

- src/ragas/metrics/_context_recall.py
> fix: context_recall example

- src/ragas/evaluation.py
- src/ragas/executor.py
- polsihed `raise_exception` which can control if you want to raise an exception or return np.nan if an error occurs
- `max_workers` can used control how many requests you do - incase you run into rate limits with ur endpoints
> fix: polishing `raise_exception` and `max_workers`

- src/ragas/llms/prompt.py
- src/ragas/testset/evolutions.py
- src/ragas/testset/prompts.py
> Convert prompts in testset generation

- src/ragas/metrics/_answer_similarity.py
Detailed description:
- Directly use the single element as the score if the similarity array has only one item, instead of attempting to extract a diagonal.
- Added a condition to check similarity.size to determine whether diagonal extraction is necessary.
- Updated unit tests to reflect this change.
Fixes #474
> Fix ValueError: diag requires an array of at least two dimensions #474

- docs/concepts/prompt_adaptation.md
- docs/howtos/applications/use_prompt_adaptation.md
> doc: modify prompt adaptation

- src/ragas/testset/evolutions.py
- src/ragas/testset/filters.py
- src/ragas/testset/generator.py
- tests/benchmarks/benchmark_testsetgen.py
usage:
```py
from ragas.testset.generator import TestsetGenerator
generator = TestsetGenerator.with_openai()
generator
from ragas.testset.evolutions import simple, reasoning, multi_context
distributions = {
simple: 0.5,
multi_context: 0.4,
reasoning: 0.1
}
distributions
testset = generator.generate_with_llamaindex_docs(documents, 100, distributions)
testset.to_pandas()
```
100 rows in <4mins 
part of #380
> feat(testset): ported simple, multi_context and reasoning evolutions

- src/ragas/embeddings/base.py
- src/ragas/evaluation.py
- src/ragas/llms/base.py
- src/ragas/llms/json_load.py
- src/ragas/llms/prompt.py
- src/ragas/metrics/_answer_correctness.py
- src/ragas/metrics/_answer_relevance.py
- src/ragas/metrics/_answer_similarity.py
- src/ragas/metrics/_context_precision.py
- src/ragas/metrics/_context_recall.py
- src/ragas/metrics/_context_relevancy.py
- src/ragas/metrics/_faithfulness.py
- src/ragas/metrics/base.py
- src/ragas/metrics/critique.py
- src/ragas/testset/evolutions.py
- src/ragas/testset/filters.py
- src/ragas/testset/generator.py
- tests/benchmarks/benchmark_eval.py
- tests/benchmarks/benchmark_testsetgen.py
Unifed the calls to LLM, embeddings and json_loader with the following logic
```py
if is_async: # just call the async version
return await self._asafe_load(text=text, llm=llm, callbacks=callbacks)
else: # call the sync version inside the event_loop
loop = asyncio.get_event_loop()
safe_load = partial(
self._safe_load, text=text, llm=llm, callbacks=callbacks
)
return await loop.run_in_executor(
None,
safe_load,
)
```
```py
async def generate(
self,
prompt: PromptValue,
n: int = 1,
temperature: float = 1e-8,
stop: t.Optional[t.List[str]] = None,
callbacks: Callbacks = [],
is_async: bool = True,
) -> LLMResult:
```
```py
async def embed_texts(
self, texts: List[str], is_async: bool = True
) -> t.List[t.List[float]]:
```
```py
async def safe_load(
self,
text: str,
llm: BaseRagasLLM,
callbacks: …
```
> feat(executor): remove the need to have both sync and async versions of the function

- src/ragas/metrics/_context_precision.py
Problem:
Root cause:
Fix:
Change the first example's 'Verdict' to small case
> Fix case for few shots of context precision metric

- docs/howtos/integrations/langchain.ipynb
Some imports were outdated since langchain's first stable version (namely v0.1.0) came out.
I also added dotenv to simplify managing the OpenAI API Key.
> Updated imports, added dotenv

- src/ragas/evaluation.py
- src/ragas/executor.py
- src/ragas/testset/docstore.py
- src/ragas/testset/generator.py
should fix the errors in Jupyter notebook but leads to bad exception tracebacks
> feat(executor): run executor in different thread to keep things clean

- src/ragas/metrics/_answer_similarity.py
Hi Ragas maintainers,
I was calculating answer similarity and noticed that my score was way above 1. I found out it was because the ground truth and generated answer embeddings were not normalized before fed into cosine similarity.
Note that this does not happen to all embeddings, only those that doesn't have L2-norm equal 1 innately.
It'd be nice if I can get some feedback and have this PR merged.
Thanks a bunch!
> add normalization factor to answer similarity score calculation

- src/ragas/metrics/_answer_correctness.py
- src/ragas/metrics/_answer_relevance.py
- src/ragas/metrics/_context_precision.py
- src/ragas/metrics/_context_recall.py
- src/ragas/metrics/_faithfulness.py
> fix: raise warning for invalid JSON

- docs/concepts/prompt_adaptation.md
- docs/howtos/customisations/gcp-vertexai.ipynb
- docs/howtos/customisations/llms.ipynb
- The code shown in the document cause warnings in the IDE.  
- `ragas.llms.LangchainLLM` is no longer exists but `from ragas.llms import LangchainLLM` is still left in [document](https://github.com/explodinggradients/ragas/blob/c9ba2be93cb698ff7e691952b6f77378b853ef58/docs/howtos/customisations/gcp-vertexai.ipynb#L128)
First time here, apology for any mistakes.
> fix wrong type annotations and nonexistent types

- docs/howtos/customisations/gcp-vertexai.ipynb
> Fixing typos, vertextai to vertex ai

- src/ragas/llms/prompt.py
Thank you for this great framework for evaluating RAG systems.
When using RAGAS, I encountered the following error while trying to adapt metrics to a specific language because the content of the output key in the elements of the `examples` attribute in the `Prompt` class was in un-parsed JSON (=str). It would be great if this PR could fix this error. I would appreciate it if you could check. Here is the error:
```
/usr/lib/python3.10/site-packages/ragas/llms/prompt.py", line 154, in get_all_keys                                 
for key, value in nested_json.items():                                                    
AttributeError: 'str' object has no attribute 'items'  
```
> Parse JSON string in adapt()

- src/ragas/llms/json_load.py
- src/ragas/metrics/_context_precision.py
- src/ragas/metrics/_faithfulness.py
Slightly broken json are protected against by the function `ragas.llms.json_load.JsonLoader._find_outermost_json`. However, I've found that for many metrics, gpt4 can often return slightly broken json lists, for which this function returns only the first valid json. Here we wrap `_find_outermost_json` with `_load_all_jsons` which calls it recursively to load the full json list.
I.e. expected output for `'{"1":"2"},  ,, {"3":"4"}]'` is `[{'1': '2'}, {'3': '4'}]`
> feat(llms.json_load): Recursively load json lists

- docs/howtos/customisations/aws-bedrock.ipynb
Testset generation using bedrock model and embeddings
> Added testset generation for bedrock

- src/ragas/evaluation.py
Since we already specify whether or not a metric requires an LLM/embeddings model via inheritence from `MetricWithLLM` and `MetricWithEmbeddings`, there isn't really a need to force the use of default LLMs/embeddings in `evaluate` if, for example, no metrics that need embeddings are specified in `metrics`. 
I believe that initiating an LLM/embedding model at the metric level will help clarify how to use `evaluate`, and will make things simpler in the future when more metrics are added as it decouples needing to initialize LLMs/embedding models for metrics that potentially don't need it. They are even optional arguments to the function itself. 
**Copilot Description**
This pull request mainly refactors the `evaluate` function in the `src/ragas/evaluation.py` file. The changes aim to …
> Made embeddings and LLMs dependent on metric in evaluate function

- src/ragas/_analytics.py
- src/ragas/testset/generator.py
- tests/unit/test_analytics.py
Fix typo
___
- Corrected a typo in the class name `TesetGenerationEvent` to `TestsetGenerationEvent` across multiple files.
- Updated all references to the corrected class name in the generator module and unit tests.
> Fix typo: Teset -> Testset

- src/ragas/metrics/__init__.py
- src/ragas/metrics/_context_entities_recall.py
This PR adds a new metric, "context_entity_recall", based on "entities" present in ground-truth and context, to evaluate retrieval mechanisms. I had discussed this metric in #482.
**Description**: 
In use cases where entities like names, places, dates etc matter, it is important that our retrieval mechanism fetches the right context, which has to be fed to the model. An example is tourism industry, names of cities, tourist places, special-dishes, etc matter quite a lot. Other examples could be health or finance domains. 
**Formulation of  `context_entity_recall`**:
I propose this new metric to be the ratio of number of entities present in `ground_truths` and `contexts` both to the number of entities present in `ground_truths` alone. This is like a measure of coverage of `ground_truth …
> feat: Add new "entity-based context recall" metric

- docs/concepts/metrics/context_entities_recall.md
- docs/concepts/metrics/index.md
- docs/references/metrics.rst
Recently I have added a new metric in #667.
This PR adds documentation for that metric.
> docs: Add docs for new entity based metric

- src/ragas/llms/prompt.py
- src/ragas/testset/evolutions.py
- src/ragas/testset/prompts.py
This seems to be the cause of #653 when LLM attempts correct the typo and end up with keys not strictly identical to "expected" keys.
> Fix typos that cause fatal assertion errors in prompts

- docs/concepts/metrics/context_precision.md
Precision@1 = 0/1 != 1. It should be 0.
This PR fixes the calculation of Precision@1 and subsequently `\text{Context Precision} = {\text{(0+0.5)} \over \text{2}} = 0.25`
> docs: Fix the precision calculation in context-precision metric doc

- docs/concepts/metrics/context_precision.md
Eventhough @amit-timalsina made a fix to the Context Precision docs a few day ago in #685  the description is still wrong in multiple ways.
1) The total number of **relevant items** is used, not all items. That is, in the example calculation the denominator needs to be 1 not 2, leading to a result of 0.5 not 0.25.
2) The formula for Context Precision@k does not show the calculation how it is actually done in code:
```python
def _calculate_average_precision(self, json_responses: t.List[t.Dict]) -> float:
score = np.nan
json_responses = [
item if isinstance(item, dict) else {} for item in json_responses
]
verdict_list = [
int("1" == resp.get("verdict", "").strip())
if resp.get("verdict")
else np.nan
for resp in json_responses
]
denominator = sum(verdict_list) + 1e-10
numerator = sum(
[ …
```
> Docs: Fix content precision description

- src/ragas/metrics/critique.py
This PR addresses an issue in the AspectCritique class where the prompt_format() method was incorrectly using a hardcoded default prompt (CRITIQUE_PROMPT.format()) for generating critique prompts. This behavior overlooked the critic_prompt field, which is intended to allow customization of the critique prompts.
Previously, attempts to customize the critique prompt for specific metrics (e.g., setting a new prompt for the harmfulness metric via harmfulness.critic_prompt = Prompt(...)) would not have the intended effect. The prompt_format() method would still return the default hardcoded prompt, thus ignoring the custom critic_prompt value.
So, I modified the prompt_format() method within the AspectCritique class to use self.critic_prompt.format() instead of CRITIQUE_PROMPT.format().
> Fix: Enable Critique Prompt Customization in AspectCritique

- docs/concepts/metrics/answer_relevance.md
The docs for the answer relevancy metric are wrong in that it is claimed that the score ranges between 0 and 1. As it is written in the calculation section an averaged cosine similarity is used to calculate the metric. The cosine similarity can range between -1 and 1. Of course, most of the time the original question and generated questions will be kind of similar in practice, leading to scores between 0 and 1, but this is not mathematically guaranteed and depends on the used embedder and how it stretches the embedding space.
The following example shows this:
```python
from ragas.metrics import AnswerRelevancy
from langchain_core import embeddings
class MyEmbeddings(embeddings.Embeddings):
embedding_lookup = { # some example embeddings
"Where is France and what is it’s capital?": [0.33, …
```
> Docs: Fix and supplement answer relevancy description

- docs/getstarted/evaluation.md
This should correct the link to the page about using your own LLMs with RAGAs. I haven't built/tested the docs locally to know if this fix actually worked, I just referenced how the other hyperlinks in the docs worked and went from there. Either way, this link is currently broken in the public docs.
> Update Bring Your Own LLM Docs Link

- src/ragas/testset/evolutions.py
This would help have a better picture of the documents that were fetched. Users can choose to drop this column if not required. But in most cases, this would be a good addition at least in the initial stages for verifying the quality of the dataset and understanding the otherwise black-box nature of the dataset generation here.
> Added metadata field to datarows

- src/ragas/metrics/_context_recall.py
In `_context_recall.py` the `is_async` flag is not passed to the `llm.generate` function, like it is done for the other metrics which leads to problems when utilising other APIs then OpenAI.
Example:
```
from ragas.metrics import context_recall
from datasets import Dataset
from ragas import evaluate
import os
os.environ["OPENAI_API_KEY"] = ""
os.environ["RAGAS_DO_NOT_TRACK"] = "true"
questions = [
"Where is France and what is it’s capital?",
]
ground_truths = [
"France is in Western Europe and its capital is Paris.",
]
contexts =[
[  
"The country is also renowned for its wines and sophisticated cuisine. Lascaux’s ancient cave drawings, Lyon’s Roman theater and", 
"The country is also renowned for its wines and sophisticated cuisine. Lascaux’s ancient cave drawings, Lyon’s Roman theater …
```
> fix: is_async not passed for llm generation in context recall

- src/ragas/testset/evolutions.py
- src/ragas/testset/extractor.py
- src/ragas/testset/prompts.py
Hi,
This fixes [issue #625](https://github.com/explodinggradients/ragas/issues/625). This issue is happening when after adaption testset generation is called. This issue is caused by the fact, that after adaption the keyword extractor returns nothing. This leads to failure later.  However the keywords are indeed extracted correctly (as can be seen when debugging) but not returned properly from the function. The key "topics" doesn't exist (after adaption) in the dict, instead it's "keyphrases". This PR works for both with/without adaption.
> Fix adapt issue for keyphrase extractor

- src/ragas/executor.py
When I call ragas in the fastapi, every time I call it, python will have an open event loop (/proc/self/fd).
> fix: Eventloop unclosed

- docs/howtos/applications/compare_embeddings.md
Going through the tutorial I found that llama_index was restructured recently (in the last month?) so these imports had to be changed to work correctly
> Update llama_index imports

- docs/howtos/applications/compare_embeddings.md
Updates the docs to reflect the correct method name.
> fix: change documentation to reflect accurate method name

- docs/getstarted/evaluation.md
The current link is not redirecting to the data_preparation doc. Changed the link to be relative similar to other working links.
> Update data_preparation doc link in evaluation.md

- docs/concepts/testset_generation.md
- docs/getstarted/testset_generation.md
- docs/howtos/applications/use_prompt_adaptation.md
- docs/howtos/customisations/azure-openai.ipynb
- docs/howtos/customisations/ragas_custom_model.ipynb
- docs/howtos/integrations/langchain.ipynb
In the example code provided in the documentation, document loaders are currently imported from `langchain` instead of `langchain_community`.
This triggers the following deprecation warnings:
```
LangChainDeprecationWarning: Importing document loaders from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:
`from langchain_community.document_loaders import DirectoryLoader`.
To install langchain-community run `pip install -U langchain-community`.
```
This PR updates the imports in the documentation from `langchain.document_loaders` to `langchain_community.document_loaders` to eliminate these warnings.
> docs: langchain.document_loaders is deprecated

- README.md
I saw that the installation step from source was unnecessarily complicated in the README.
I simplified it, following patterns using in most other large python package frameworks.
I also changed the text around to make it clearer to the user what each step does.
> Cleaned installation step in README

- src/ragas/metrics/critique.py
I've made some minor improvements to the [critique prompt](https://github.com/explodinggradients/ragas/blob/main/src/ragas/metrics/critique.py) questions to ensure they are grammatically correct and clear.
The details of this issue were captured in #971 
- Updated the verbs to their base forms to align with the auxiliary verbs "does" and "is." This ensures proper agreement and clarity in the questions. This change was applied to these critique questions:
- Harmfulness
- Maliciousness
- Coherence
- Conciseness
- Added a question mark to the end of the conciseness critique question.
- Removed extra space in critique prompt example
> Improve grammar and punctuation in critique prompts: addresses #971

- src/ragas/testset/generator.py
This pull request addresses an issue in the TestsetGenerator where the chosen contexts for evolutions were not being sampled correctly because only the very first contexts were selected. Now, the selection can potentially choose any context
> Fix testset generator issue on context selection

- docs/howtos/integrations/llamaindex.ipynb
- src/ragas/embeddings/__init__.py
- src/ragas/embeddings/base.py
- src/ragas/executor.py
- src/ragas/integrations/llama_index.py
- src/ragas/llms/__init__.py
- src/ragas/llms/base.py
- src/ragas/llms/prompt.py
- src/ragas/metrics/_context_relevancy.py
- src/ragas/metrics/base.py
- src/ragas/testset/generator.py
- src/ragas/validation.py
- tests/benchmarks/benchmark_testsetgen.py
- tests/e2e/test_amnesty_in_ci.py
> Feat/llamaindex: adding llamaindex

- src/ragas/evaluation.py
- src/ragas/metrics/base.py
- src/ragas/run_config.py
The current version of `evaluation` contains a threading timeout issue refered in issue #854 #722 #734 #810, which makes the evaluation process hangs in the last few cases and won't finish running.
This PR adds a `threading_timeout` parameter in the run_config, which raises asyncio.TimeoutError when the metric ascore function runs over the `threading_timeout`, avoiding the forever hanging situation.
> bugfix: evaluation thread timeout

- docs/concepts/metrics/index.md
- docs/concepts/metrics/summarization_score.md
- docs/conf.py
- docs/references/metrics.rst
**Description**: This PR adds docs for the recent summarization metric that I created in [this PR](https://github.com/explodinggradients/ragas/pull/990)
> Docs for summarization metric

- src/ragas/metrics/__init__.py
- src/ragas/metrics/utils.py
- tests/unit/test_metric.py
Based on databaset column, it tries to return all available metrics which are suitable for evalution
> adding `get_available_metrics` method

- src/ragas/testset/evolutions.py
- src/ragas/testset/generator.py
fixes #848 
This pull request introduces updates to the TestsetGenerator and ComplexEvolution classes within the generator.py and evolutions.py files respectively. The primary focus of these changes is to improve the handling of new documents during test dataset generation, ensuring that data from previous documents does not interfere with the generation process.
Here row 2 and 4 are generated from the document used for the previous generation
Here all rows generated are based on the new document provided
> fix(testset): for generating testset with new docs

- src/ragas/executor.py
Fixes #956
Explanation: https://github.com/explodinggradients/ragas/issues/956#issuecomment-2111866001 
Code for testing: https://github.com/explodinggradients/ragas/issues/956#issuecomment-2112453657
> Fix counter in Runner and Executor in case of any exception

- src/ragas/executor.py
In issue #963 I commented about the RuntimeError when trying to use TestsetGenerator. 
In issue  #681 you discussed that using get_event_loop() was the optimal way to solve the issue but it had a Deprecation warning. 
In newer python versions get_event_loop() raises a RuntimeError when no event loop is active. Thus we can avoid creating unnecessary new loops that seem to be the problem that was mentioned in both issues. 
I have modified the code the least possible to make it clear what I intended to, although in this setup runner could be avoided as was proposed in #689 
Setup: 
Ragas version: 0.1.7
Python version: Python 3.10.13
> Chore: Fix RuntimeError: ... got Future <..> attached to a different loop

- src/ragas/integrations/langchain.py
- src/ragas/utils.py
- When you are using a custom llm or embeddings with langchain EvaluatorChain and you have not set OpenAI's ENVs, a validation error is raised for missing ENVs
> fix: langchain EvaluatorChain OpenAI validation error

- src/experimental/ragas_experimental/testset/generators/simple.py
- src/ragas/_analytics.py
- src/ragas/testset/generator.py
there is also a fix for `TestData` rename
> chore: added analytics to count the num of testsets generated with experimental

- src/experimental/ragas_experimental/testset/generators/base.py
Prevents a ValueError on py3.12
> Fix mutable dataclass defaults

- Makefile
- requirements/test.txt
- src/ragas/executor.py
- tests/unit/test_executor.py
- tests/unit/test_executor_in_jupyter.ipynb
ragas `0.1.10` broke how the executor was functioning and there were a few hard to reproduce bugs overall. This fixes all those.
- uses `nest_asyncio` in jupyter notebooks 
- added tests in jupyter notebook with `nbmake`
- removed the Runner. this means all the `Tasks` will be run in the same event loop as main. for jupyter notebooks we will use `nest_async` lib
takes inspiration from #689 
fixes: #681
> fix(executor): simplify executor by removing threading

- src/ragas/testset/evolutions.py
The task of creating test datasets for different languages.
*Steps:*
1.  install requirements: `pip install git+https://github.com/explodinggradients/ragas`
2.  init generator:
```python
from llama_index.core.base.embeddings.base import BaseEmbedding
from llama_index.core.base.llms.base import BaseLLM
from ragas.testset.evolutions import ConditionalEvolution, MultiContextEvolution, ReasoningEvolution, SimpleEvolution
from ragas.testset.generator import TestsetGenerator
generator_llm = BaseLLM(...)
critic_llm = BaseLLM(...)
embeddings = BaseEmbedding(...)
generator: TestsetGenerator = TestsetGenerator.from_llama_index(
generator_llm=generator_llm, critic_llm=critic_llm, embeddings=embeddings
)
simple = SimpleEvolution(max_tries=1)
multi_context = MultiContextEvolution(max_tries=1) …
```
> [Fix bug] The adaptation for `rewrite_invalid_question_prompt` was not saved

- src/ragas/utils.py
Error when retrieving values from dictionary
> [Fix bug] utils.py

- docs/concepts/metrics/context_recall.md
This PR fixes the docs for the context recall metric by renaming "sentence" to "claim". A minor formatting fix is included, too.
> Fix "sentence" -> "claim" the context recall metric docs

- src/ragas/run_config.py
- src/ragas/testset/docstore.py
- src/ragas/testset/evolutions.py
Should fix https://github.com/explodinggradients/ragas/issues/1140
Allow a user to fix the seed him/herself and use a random seed otherwise.
Define the seed as an initial attribute and the rng as a post_initialization attribute that a user can override and adapt its use in ragas.testset.docstore.InMemoryDocumentStore and ragas.testset.evolutions.Evolution
> Random seed fixed.

- docs/howtos/applications/compare_embeddings.md
The code examples from `docs/howtos/applications/compare_embeddings.md` were missing important lines e.g. missing the `TestsetGenerator` import and assigning `test_df` before using it.
This pull request adressess these minor improvements.
> Fixing Demo Code - Compare Embeddings for retriever Docs

- src/ragas/metrics/_faithfulness.py
Fixed problem with statement_prompt not being saved in cache when applying language adapter to faithfulness
> Add save function for statement_prompt

- docs/getstarted/evaluation.md
- docs/getstarted/testset_generation.md
- docs/howtos/customisations/index.md
- docs/howtos/customisations/ragas_custom_model.ipynb
- docs/howtos/customisations/run_config.ipynb
- docs/references/index.rst
- docs/references/run_config.rst
- src/ragas/evaluation.py
- src/ragas/executor.py
- src/ragas/integrations/llama_index.py
- src/ragas/metrics/base.py
- src/ragas/run_config.py
- src/ragas/utils.py
- tests/unit/test_executor.py
- added documentation for `RunConfig`
- made `raise_exceptions=False` as default in `evaluate()`
- renamed `RunConfig.thread_timeout` to `timeout`
> fix: `RunConfig` documentation and improvements

- src/ragas/llms/base.py
- src/ragas/testset/generator.py
Reasons
1. gpt4o-mini is 2x cheaper than the current default model of gpt3.5-turbo
2. Extended context length of 128k tokens
3. All the public benchmarks indicate better performance on all tasks by gpt4o-mini compared to gpt3.5-turbo. [Source](https://openai.com/index/gpt-4o-mini-advancing-cost-efficient-intelligence/)
> change default model to gpt4o-mini

- tests/unit/test_run_config.py
Previous exchanges about the `numpy.random.Generator` (#1140, #1142 and #1152) led to the need to implement some tests. Previous ones had been setup but a more precise definition of the context box might strengthen the confidence in the overall generation.
Check the ability to generate a specific `numpy.random.Generator`, its fixed behaviour between generations and its consistency accross module reloads but also the actual random generation when the `seed` is set to `None`.
Pytest with 2 parametrized test: 1 with the `seed` fixed, the other one with `seed` set to `None`. Each test will check whether the generation is fixed, reproductible and consistent according to the seed.
> Add tests to `ragas.run_config.RunConfig` `rng` attribute.

- .github/workflows/ci.yaml
- src/ragas/metrics/base.py
- tests/e2e/test_evaluation_in_jupyter.ipynb
- tests/unit/test_executor_in_jupyter.ipynb
- tests/unit/test_metric.py
I got errors when running metrics within an existing asyncio loop, the `asyncio.run` part makes the code fail in those cases. Submitting a bugfix.
> Allow Metric.score to work within an existing asyncio loop

- docs/concepts/metrics/context_recall.md
> Add question to context recall doc

- docs/howtos/integrations/helicone.ipynb
Tested and working integration with Helicone
> Helicone Integration

- DEVELOPMENT.md
The development.md file previously suggested using make tests to run the tests. However, the [Makefile](https://github.com/explodinggradients/ragas/blob/main/Makefile#L28C1-L28C19) does not include a target named tests, which results in the error make: Nothing to be done for 'tests'. This commit updates the documentation to reflect the correct command for running tests, ensuring alignment with the existing Makefile configuration.
> Fix test command in development.md to match Makefile configuration

- docs/concepts/metrics/index.md
- docs/concepts/metrics/rubrics_based.md
> docs: rubrics based metrics

- docs/concepts/index.md
A non-urgent, non-critical fix from contraction to possessive.
Elsewhere there is also an "it's" in `Question: Where is France and what is it's capital?`, but since that's a prompt a human might reasonably type, and in the answer "its" is used correctly, I thought it didn't need to be fixed.
> Tiny typo fix: it's -> its

- src/ragas/validation.py
Sets `EVALMODE_TO_COLUMNS[EvaluationMode.ca] =  ["contexts", "answer"]` in `src/ragas/validation.py` to fix #1215.
> fix : solves #1215 - Inconsistency in the Value of EVALMODE_TO_COLUMNS[EvaluationMode.ca]

- src/ragas/integrations/llama_index.py
Dict in dataset of the evaluate function specified. Does not work -> Dataset and then check of "ground_truth" in column_names.
> Bugfix of evaluate function in llama_index.py

- src/ragas/metrics/_faithfulness.py
Allow users to specify the device to load HHEM and add `_create_batch` to avoid OOM
> load HHEM on specified device

- src/ragas/evaluation.py
- src/ragas/executor.py
Hello there :wave: I noticed that there was no way to disable the progress bar and thought it'd nice to have the option to silence the `tqdm` call in the executor, as it doesn’t play nicely with logs and adds noise.
I've added the following changes:
Add `show_progress` flag to `Executor` class and update `evaluate` function to use it.
* **Executor Class Changes:**
- Add `show_progress` flag to the `Executor` class in `src/ragas/executor.py`.
- Use the `show_progress` flag to control the display of the progress bar.
- If `show_progress` is set to False, disable `tqdm` usage for displaying progress bars.
* **Evaluate Function Changes:**
- Add `show_progress` parameter to the `evaluate` function in `src/ragas/evaluation.py`.
- Pass the `show_progress` flag to the `Executor` class during …
> Add option to disable progress bar in `evaluate`

- src/ragas/metrics/_simple_criteria.py
```python
from ragas.dataset_schema import SingleTurnSample
from ragas.metrics._simple_criteria import SimpleCriteriaScoreWithoutReference
sample = SingleTurnSample(
user_input="Where is the Eiffel Tower located?",
response="The Eiffel Tower is located in Paris.",
)
scorer =  SimpleCriteriaScoreWithoutReference(name="course_grained_score", definition="Score 0 to 5 for correctness")
scorer.llm = openai_model
await scorer.single_turn_ascore(sample)
```
> feat: add simple scorer metric

- src/ragas/experimental/metrics/_faithfulness.py
- src/ragas/metrics/_context_precision.py
ValueError: The metric [context_utilization] that that is used requires the following additional columns ['retreived_contexts'] to be present in the dataset.
> Fix wrong input key name

- pyproject.toml
- src/ragas/integrations/opik.py
The new langchain v0.3 will break the current usage of metrics. 
the plan for actions is as follows
1. for ragas<0.2 we will pin langchain_core to <0.3
2. for ragas>0.2 we will directly depend on pydantic>=2
fixes: #1328
> fix: pin langchain_core to <3

- src/ragas/dataset_schema.py
- src/ragas/metrics/_tool_call_accuracy.py
```python
from ragas.dataset_schema import  MultiTurnSample
from ragas.messages import HumanMessage,AIMessage,ToolMessage,ToolCall
from ragas.metrics._tool_call_accuracy import ToolCallAccuracy
sample = MultiTurnSample(user_input=[
HumanMessage(content="Hey, book a table at the nearest best Chinese restaurant for 8:00pm"),
AIMessage(content="Sure, let me find the best options for you.", tool_calls=[
ToolCall(name="restaurant_search", args={"cuisine": "Asian", "time": "8:00pm"})
]),
],
reference_tool_calls=[ToolCall(name="restaurant_book", args={"name": "Golden", "time": "8:00pm"})
])
scorer = ToolCallAccuracy()
await metric.multi_turn_ascore(sample)
```
> feat: tool call accuracy

- docs/concepts/metrics/sql.md
- pyproject.toml
- requirements/dev.txt
- src/ragas/metrics/_datacompy_score.py
- src/ragas/metrics/_sql_semantic_equivalence.py
```python
from ragas.metrics._datacompy_score import DataCompyScore
from ragas.dataset_schema import SingleTurnSample
data1 = """acct_id,dollar_amt,name,float_fld,date_fld
10000001234,123.45,George Maharis,14530.1555,2017-01-01
10000001235,0.45,Michael Bluth,1,2017-01-01
10000001236,1345,George Bluth,,2017-01-01
10000001237,123456,Bob Loblaw,345.12,2017-01-01
10000001238,1.05,Lucille Bluth,,2017-01-01
10000001238,1.05,Loose Seal Bluth,,2017-01-01
"""
data2 = """acct_id,dollar_amt,name,float_fld
10000001234,123.4,George Michael Bluth,14530.155
10000001235,0.45,Michael Bluth,
10000001236,1345,George Bluth,1
10000001237,123456,Robert Loblaw,345.12
10000001238,1.05,Loose Seal Bluth,111
"""
sample = SingleTurnSample(response=data1, reference=data2)
scorer = DataCompyScore(metric="precision", …
```
> feat: sql sementic equivalence

- src/ragas/executor.py
- tests/unit/test_executor.py
- tests/unit/test_executor_in_jupyter.ipynb
Originally as_complete is not defined with async, the asyncio.Semaphore is created in main thread not in asynci.run. This will cause 'There is no event loop' error when: 
1. len(coros) is more than max_workers; 
2. run 'evalute' function at the second time and nest_asyncio is not applied.
> wrap as_complete with async

- docs/concepts/testset_generation.md
- docs/howtos/applications/compare_embeddings.md
- docs/howtos/applications/compare_llms.md
- docs/howtos/applications/use_prompt_adaptation.md
According to the OpenAI API reference, As of July 2024, gpt-4o-mini should be used in place of gpt-3.5-turbo, as it is cheaper, more capable, multimodal, and just as fast. gpt-3.5-turbo is still available for use in the API, but the advantages of gpt-4o-mini make it a better choice.
Additionally, the cost of using gpt-4 in the API is too high. Switching to gpt-4o is a more economical option without compromising performance. Personally, I had a significant chunk of my credits consumed due to the high cost of gpt-4 😢.
> Update models in Ragas documentation: change gpt-3.5-turbo-16k to gpt-4o-mini and gpt-4 to gpt-4o

- docs/concepts/metrics/general_purpose.md
fixes #1374 
but a couple of things to note here
- metrics should exposed from `ragas.metrics` because all our metrics modules are private with `_` prefix. 
- need to mention this in the migration guide, about aspect critic
> fix: aspect_critique documentation

- src/ragas/testset/evolutions.py
The bug is located in the ragas.testset.Evolution class. The problem is that you are checking the ‘verdict’ field against a string value of ‘-1’, and you need to compare it against an int value of -1:
So I changed the verdict comparison from a string to an integer in the conditional check.
> fix: fixed verdict comparison in evolutions.py

- src/ragas/dataset_schema.py
- src/ragas/experimental/testset/simulators/__init__.py
- src/ragas/experimental/testset/simulators/abstract_qa.py
- src/ragas/experimental/testset/simulators/base.py
- src/ragas/experimental/testset/simulators/generate.py
- src/ragas/experimental/testset/simulators/testset_schema.py
- src/ragas/metrics/_answer_relevance.py
> feat: output new Testset object for generation

- src/ragas/metrics/_faithfulness.py
- src/ragas/metrics/_noise_sensitivity.py
There is a bug with json.dumps: non-ascii charecters are converting into non-readable symbols.
It affects Faithfulness and NoiseSensitivity only.
> non-asii characters support in faithfulness

- src/ragas/experimental/prompt.py
- src/ragas/experimental/testset/simulators/base.py
- src/ragas/experimental/testset/transforms/base.py
- src/ragas/metrics/base.py
```python
from ragas.experimental.testset.simulators import AbstractQuestionSimulator
simulator = AbstractQuestionSimulator()
prompts = simulator.get_prompts()
prompts['common_theme_prompt'].instruction += "\n Ouptut only JSON"
simulator.set_prompts(common_theme_prompt=prompts['common_theme_prompt'])```
> feat:  get and set prompts mixin

- src/ragas/validation.py
This pull request addresses a minor typo in the error message related to metric validation. The message previously contained a duplicated "that," which has been corrected for clarity.
> Fix typo in metric error message

- src/ragas/metrics/_faithfulness.py
The current implementation for evaluating FaithfullnessWithHHEM requires legacy 'contexts' key and would throw out key error. This simple fix would resolve the issue.
> fix key error for FaithfulnesswithHHEM

- docs/extra/components/choose_evaluvator_llm.md
- docs/howtos/customizations/customize_models.md
Updating LangChain modules for Amazon Bedrock (AWS) in "customizations" section.
- Use `langchain_aws` instead of `langchain_community.`
- Use `ChatBedrock` instead of `BedrockChat`
> Update Bedrock modules for LangChain v0.3.x

- docs/getstarted/rag_testset_generation.md
- Edit the document because the name testset_size is used in the generate_with_langchain_docs function
- ragas/testset/synthesizers/generate.py
```
def generate_with_langchain_docs(
self,
documents: t.Sequence[LCDocument],
testset_size: int,
transforms: t.Optional[Transforms] = None,
...
```
> docs: Change test_size parameter name to testset_size

- src/ragas/prompt/pydantic_prompt.py
Callbacks are now correctly passed to `fix_output_format_prompt.generate()` during output format fixing in `RagasOutputParser`.
> fix: propagate callbacks in RagasOutputParser

- src/ragas/testset/graph.py
To avoid \u escape sequences in KnowledgeGraph json files and have clean readable text for non-ASCII chars.
related to #1022
> feat: use ensure_ascii=False for KnowledgeGraph files

- docs/concepts/metrics/available_metrics/summarization_score.md
There is mismatch how coeff is used in docs vs actual computation.
Related code is in:
https://github.com/explodinggradients/ragas/blob/889fe2b9181baf203ca96fa876a54c7d80989767/src/ragas/metrics/_summarization.py#L189
> docs: update summarization calculation

- src/ragas/llms/base.py
Matches the behavior in agenerate, avoiding some API call failures
> fix: use get_temperature in base LLM generate

- docs/howtos/customizations/metrics/_modifying-prompts-metrics.md
- docs/howtos/customizations/metrics/modifying-prompts-metrics.ipynb
- Remove extra text from output example
- Add missing `want` into the sentence
`docs/howtos/customizations/metrics/_modifying-prompts-metrics.md`
- Only 1 `Only output valid JSON.` should be part of the output.
> doc: Update modifying prompts metrics doc

- src/ragas/metrics/_faithfulness.py
**Description**
This pull request addresses an issue where non-English punctuation (e.g., "。", "！") was not properly handled in the `_create_statements` function, causing sentences in languages like Chinese to be ignored and potentially leading to incorrect faithfulness scores.
**Changes Made**
Updated the condition:
```python
if sentence.strip().endswith("."):
```
to
```python
if sentence.strip().endswith(('.', '。', '!', '！')):
```
This ensures that sentences with non-English punctuation are included in the processing.
**Impact**
This change allows the system to correctly process sentences in languages like Chinese, preventing empty `sentences_with_index` variables and ensuring accurate faithfulness scores.
---
Let me know if this works or if you need further edits! Thanks!
> fixbug: Expand sentence-ending punctuation check in _create_statements method

- src/ragas/callbacks.py
- src/ragas/dataset_schema.py
- src/ragas/evaluation.py
- src/ragas/metrics/_aspect_critic.py
- src/ragas/metrics/_faithfulness.py
- src/ragas/metrics/base.py
- src/ragas/prompt/pydantic_prompt.py
- tests/unit/test_metric.py
> feat: add traces to `EvaluationResult`

- src/ragas/prompt/mixin.py
- src/ragas/prompt/pydantic_prompt.py
When adapting prompts, both the examples and the corresponding instructions are important and need to be translated.
> feat: translate instruction when adapting prompt

- src/ragas/prompt/pydantic_prompt.py
- src/ragas/prompt/utils.py
- tests/unit/prompt/test_prompt_utils.py
Fixes #1538 
- Add final instruction for better json schema adherence and reduce "filler" text
- Add `extract_json` function to identify json by pairs of `[]` or `{}`
- Add unit tests for `extract_json`
**Notes:**
In my testing, these changes vastly reduce the number of times the 'repair' agent is triggered.  However, this does not fix _all_ parse errors:
1. In some cases, json is valid json, but keys are invalid
2. In some cases, especially with more complex Pydantic models (e.g., `Themes`, which is composed of `List[Theme]`), the Pydantic json schema includes `$defs`.  As a result, some LLMs will return `$defs` or include `"$schema": "https://json-schema.org/draft/...`; either of these additional keys will cause the Pydantic parser to fail.
> Fix: Resolve Agentic failure loop with improved json parsing

- docs/getstarted/rag_testset_generation.md
- docs/howtos/applications/_cost.md
- docs/howtos/applications/cost.ipynb
- src/ragas/dataset_schema.py
- src/ragas/testset/synthesizers/base_query.py
- src/ragas/testset/synthesizers/generate.py
- src/ragas/testset/synthesizers/specific_query.py
- src/ragas/testset/synthesizers/testset_schema.py
- src/ragas/testset/transforms/engine.py
- tests/unit/test_dataset_schema.py
fixes #1527 
adds a cost estimator to testset generation
> feat: measure cost of testset generator

- src/ragas/metrics/__init__.py
To use LLMContextPrecisionWithReference metric from user program, add "LLMContextPrecisionWithReference" to __init__.py in metrics directory.
> Fix: add LLMContextPrecisionWithReference to __init__.py

- src/ragas/exceptions.py
- src/ragas/prompt/pydantic_prompt.py
- tests/unit/test_prompt.py
When parsing of an LLM response fails, the invalid output is sent to the LLM to be fixed.
This PR threads the number of retries through this call, preventing unbounded recursion.
The old `max_retries` wasn't preventing this due to `generate()` and `parse_output_string()` being co-recursive via the call to `generate()` here
https://github.com/explodinggradients/ragas/blob/ade46fb7c0b5dffb76ef26d876ff021ded9dfa96/src/ragas/prompt/pydantic_prompt.py#L406
The result was a prompt that would keep growing through recursive calls (with nested versions becoming increasingly more deeply quoted) until the prompt was too big for the LLM to process.
Addresses https://github.com/explodinggradients/ragas/issues/1538
> Fix: Limit number of retries for parse failures

- docs/concepts/metrics/available_metrics/index.md
- docs/concepts/metrics/available_metrics/multi_modal_faithfulness.md
- docs/concepts/metrics/available_metrics/multi_modal_relevance.md
- src/ragas/exceptions.py
- src/ragas/metrics/__init__.py
- src/ragas/metrics/_multi_modal_faithfulness.py
- src/ragas/metrics/_multi_modal_relevance.py
- src/ragas/prompt/__init__.py
- src/ragas/prompt/multi_modal_prompt.py
- src/ragas/prompt/pydantic_prompt.py
- src/ragas/testset/synthesizers/generate.py
- tests/unit/test_prompt.py
I am a developer from [ModelScope](https://github.com/modelscope/modelscope). This framework is great and I would like to add some new features. Multi-modal RAG evaluation is important, as mentioned in https://github.com/explodinggradients/ragas/issues/1030. 
This PR adds support for image-text context RAG evaluation. Currently, it preliminarily supports MultiModalFaithfulness and MultiModalRelevance by referring to LlamaIndex (reference: [faithfulness](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/evaluation/multi_modal/faithfulness.py) and [relevancy](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/evaluation/multi_modal/relevancy.py)).  *The current evaluation metrics are still quite preliminary and can be …
> Feat: add multimodal eval support

- src/ragas/metrics/_topic_adherence.py
An attempt to fix https://github.com/explodinggradients/ragas/issues/1564
Let me know if my PR is lack of something else
> fix: add `reference_topics` as default required columns in `TopicAdherenceScore` #1564

- src/ragas/metrics/_factual_correctness.py
This pull request optimizes the `_single_turn_ascore` function by conditionally skipping unnecessary computations when the mode is set to "precision." Previously, the function calculated `response_reference` regardless of the scoring mode, which consumed resources and potentially increased processing costs. By avoiding the `response_reference` calculation in "precision" mode, this update aims to enhance speed and reduce computational expenses.
- Modified `_single_turn_ascore` function:
- **Conditionally calculated `response_reference`**: The `response_reference` is now computed only when the mode is not "precision."
> Improve efficiency in factual correctness for precision mode

- src/ragas/metrics/__init__.py
- src/ragas/metrics/_rouge_score.py
Fixes the typo 'rogue' with referring to 'rouge' score.
Because this changes a file name and param name, it can be considered a breaking change
> fix: typo: ROUGE is a metric, ROGUE is a scoundrel

- src/ragas/llms/base.py
Add Anthropic signature to LlamaIndexLLMWrapper.  Fixes #1468.
Question for maintainers -- would it make sense to always set `LlamaIndexLLMWrapper._signature` for all models rather than having a series of conditionals?  i.e. (line 269):
```py
269 | self._signature = type(self.llm).__name__.lower()
```
The rest of the logic in `check_args` to handle different param dicts can remain.
> fix: treat anthropic-direct API the same as bedrock in llamaindex wrapper

- docs/getstarted/rag_testset_generation.md
- edit the document because embedding_model attribute has been added to the TestsetGenerator object.
- https://github.com/explodinggradients/ragas/pull/1562
> docs: Add embedding_model attribute when creating TestsetGenerator object

- src/ragas/llms/base.py
My case
- When receiving responses from headline and summary extractors, etc., they are delivered as a Generation object, not ChatGeneration.
```
{
"generations": [
[
{
"text": "{\"text\": \"ABCD\"}",
"generation_info": null,
"type": "Generation"
}
]
],
"llm_output": null,
"run": null,
"type": "LLMResult"
}
```
Occurrence message
- unable to apply transformation: 'Generation' object has no attribute 'message'
How to fix
- Add code to first check if it is an instance of that object before casting to a ChatGeneration object.
> Fix: Add instance check before casting ChatGeneration object

- docs/community/index.md
I updated the community blog posts and added the Ragas v0.2 guide with [EvalScope](https://github.com/modelscope/eval-scope) in Chinese : )
> docs: add community docs

- src/ragas/metrics/_answer_similarity.py
Fixes: #996 
Some embedding models do not work with empty strings (for example Gemini) and return an error.
The error does not appear with OpenAI which returns an embeddings even for an empty string.
Proposed resolution: replace empty strings with `" "`
> Handle embeddings for empty strings in AnswerSimilarity class

- src/ragas/metrics/_topic_adherence.py
This only affects `src/ragas/_topic_adherece.py`.
Previously, it can be complicated to handle the score given by this metric due to possibility of division by zero. I propose to introduce an epsilon in the denominator to avoid that case.
> Introduce epsilon in denominators to avoid division by zero

- src/ragas/metrics/_noise_sensitivity.py
Fix #1626 to support more languages.
> fix: remove `.` as a split condition in noise_sensitivity.py

- src/ragas/metrics/_bleu_score.py
- src/ragas/metrics/_factual_correctness.py
- src/ragas/metrics/_topic_adherence.py
As title. The usage of sentence_segmenter for some indicators is not uniform.
> feat: Unify the use of sentence_segmenter

- docs/extra/components/choose_evaluator_llm.md
found this small error while trying to use ragas following the starter guide using azure openai
previously set azure_config should be referenced instead of azure_configs (which doesn't exist)
> fixed wrong variable names in starter guide using azure openai

- src/ragas/testset/graph.py
- src/ragas/testset/graph_queries.py
- src/ragas/testset/transforms/__init__.py
- src/ragas/testset/transforms/base.py
- src/ragas/testset/transforms/default.py
- src/ragas/testset/transforms/extractors/llm_based.py
- src/ragas/testset/transforms/filters.py
- src/ragas/testset/transforms/splitters/headline.py
1. Add node filtering mechanism
2. Add min and max tokens in headline splitting
> feat: improvements in test gen

- src/ragas/metrics/_factual_correctness.py
Bug fixing recall in factual correctness:
recall is equal to: tp / (tp + fn)
but was calculated exactly like the precision.
Reference: https://docs.ragas.io/en/latest/concepts/metrics/available_metrics/factual_correctness/#factual-correctness
> Bug fixing recall in  _factual_correctness.py

- src/ragas/metrics/_factual_correctness.py
Avoid unnecessary decompose_claims call when mode='precision' in FactualCorrectness.
> Avoid unnecessary decompose_claims call when mode='precision' in _factual_correctness.py

- src/ragas/prompt/pydantic_prompt.py
New formating example. 
```
Given a input and response. Evaluate the submission only using the given criteria. Use only 'Yes' (1) and 'No' (0) as verdict.
Please return the output in a JSON format that complies with the following schema as specified in JSON Schema:
{'properties': {'reason': {'description': 'Reason for the verdict', 'title': 'Reason', 'type': 'string'}, 'verdict': {'description': 'The verdict (0 or 1) for the submission', 'title': 'Verdict', 'type': 'integer'}}, 'required': ['reason', 'verdict'], 'title': 'AspectCriticOutput', 'type': 'object'}
--------EXAMPLES-----------
Example 1
Input: {
"user_input": "Who was the director of Los Alamos Laboratory?",
"response": "Einstein was the director of Los Alamos Laboratory.",
"criteria": "Is the output written in perfect grammar" …
```
> fixes:  instruction format

- src/ragas/metrics/_answer_correctness.py
- src/ragas/metrics/_answer_similarity.py
- `SemanticSimilarity` is not an LLM metric, so it doesn't have to extend `MetricWithLLM`
> removed MetricWithLLM from SemanticSimilarity

- docs/getstarted/rag_testset_generation.md
The code in rag_testset_generation.md code not compile and contains 2 syntax errors (API has changed)
I now added missing possitional arguments for embedding_model and documents
> Bug in documentation rag_testset_generation.md: API changes required arguments

- src/ragas/metrics/__init__.py
- src/ragas/metrics/_answer_correctness.py
- src/ragas/metrics/_answer_relevance.py
- src/ragas/metrics/_answer_similarity.py
- src/ragas/metrics/_aspect_critic.py
- src/ragas/metrics/_context_entities_recall.py
- src/ragas/metrics/_context_precision.py
- src/ragas/metrics/_context_recall.py
- src/ragas/metrics/_domain_specific_rubrics.py
- src/ragas/metrics/_factual_correctness.py
- src/ragas/metrics/_faithfulness.py
- src/ragas/metrics/_goal_accuracy.py
- src/ragas/metrics/_instance_specific_rubrics.py
- src/ragas/metrics/_multi_modal_faithfulness.py
- src/ragas/metrics/_multi_modal_relevance.py
- src/ragas/metrics/_noise_sensitivity.py
- src/ragas/metrics/_simple_criteria.py
- src/ragas/metrics/_sql_semantic_equivalence.py
- src/ragas/metrics/_summarization.py
- src/ragas/metrics/_topic_adherence.py
- src/ragas/metrics/base.py
Added output_type as optional parameter to LLM based metrics to derive the loss required for optimising the metric. This feature can also be later used to change the UI layout when we introduce ranking based metrics.
> feat: add output type to metrics

- src/ragas/executor.py
I went through hoops the last hr to try a few things to fix the issue documented in #1718 (except `MultiHopAbstractQuerySynthesizer` and `MultiHopSpecificQuerySynthesizer`). 
This PR proposes the most trivial fix. But it fixes this test generation issue:
```
from langchain_community.document_loaders import DirectoryLoader
from ragas.testset import TestsetGenerator
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI
from langchain_openai import OpenAIEmbeddings
path = "Sample_Docs_Markdown/"
loader = DirectoryLoader(path, glob="**/*.md")
docs = loader.load()
generator_llm = LangchainLLMWrapper(ChatOpenAI(model="gpt-4o"))
generator_embeddings = LangchainEmbeddingsWrapper(OpenAIEmbeddings())
generator = …
```
> fix: attempting a simple fix for #1718

- src/ragas/llms/base.py
This PR adds proper completion detection support for Google's Vertex AI Gemini models in the LangchainLLMWrapper class. Currently, Ragas systematically raises `LLMDidNotFinishException` with Gemini models because it doesn't correctly interpret Gemini's completion signals.
The current implementation in `LangchainLLMWrapper` doesn't properly handle Gemini's completion signals:
- Gemini uses "STOP" and "MAX_TOKENS" as valid completion reasons
- The completion status can be found in either generation_info or response_metadata
- The current logic doesn't account for these Gemini-specific patterns
1. Modified is_finished class to support completion detection for Gemini models. Added proper handling of Gemini's completion signals
2. 
1. Modified `LangchainLLMWrapper` in `ragas/llms/base.py`: …
> Added native support for Gemini models generation completion signals in LangchainLLMWrapper class / is_finished method

- .gitignore
- pyproject.toml
- src/ragas/config.py
- src/ragas/dataset_schema.py
- src/ragas/executor.py
- src/ragas/metrics/base.py
- src/ragas/optimizers/genetic.py
- src/ragas/prompt/__init__.py
- src/ragas/prompt/few_shot_pydantic_prompt.py
- src/ragas/prompt/pydantic_prompt.py
- tests/unit/test_prompt.py
optimize with few short examples
```py
from ragas.metrics import AspectCritic
from ragas.llms import llm_factory
llm = llm_factory("gpt-4o")
metric = AspectCritic(
name="answer_correctness",
definition="Given the user_input, reference and response. Is the response correct compared with the reference",
llm=llm,
)
from ragas.config import DemonstrationConfig
demonstration_config = DemonstrationConfig()
metric.train(
"alignment_sample.json",
demonstration_config=demonstration_config,
)
```
> feat: few shot example optimzier

- docs/concepts/metrics/available_metrics/traditional.md
- requirements/dev.txt
- src/ragas/metrics/_bleu_score.py
NLTK's implementation of BLEU is limited. In particular, only 20% of my attempts to compute BLEU return a score because the number of candidate and reference sentences are not the same, a requirement of NLTK's implementation. The implementation of BLEU by [sacrebleu](https://github.com/mjpost/sacrebleu) is recommended because it is more robust. In my PR, I have modified _bleu_score.py to use sacrebleu's implementation.
> feat: replaced NLTK's implementation of BLEU with sacrebleu's implementation

- docs/howtos/applications/_metrics_llm_calls.md
- src/ragas/metrics/_simple_criteria.py
fixes: https://github.com/explodinggradients/ragas/pull/1758
> fix: add reference to simple scoring

- src/ragas/metrics/_context_recall.py
```python
from ragas import evaluate
from ragas.metrics import NonLLMContextRecall, NonLLMContextPrecisionWithReference
from ragas import SingleTurnSample, EvaluationDataset
from ragas.metrics._string import DistanceMeasure
sample = SingleTurnSample(
retrieved_contexts=["Paris is the capital of France."], 
reference_contexts=["Paris is the capital of France.", "The Eiffel Tower is one of the most famous landmarks in Paris."]
)
dataset = EvaluationDataset(samples=[sample, sample, sample])
scorer = NonLLMContextRecall()
result = evaluate(
dataset,
metrics=[scorer],
)
scorer.distance_measure = DistanceMeasure.JARO_WINKLER
result = evaluate(
dataset,
metrics=[scorer],
)```
> fix: distance measure in non llm CR

- docs/concepts/metrics/available_metrics/general_purpose.md
Issue: Differences between tutorials and source code in **General Purpose Metrics**
link : https://docs.ragas.io/en/latest/concepts/metrics/available_metrics/general_purpose/
Two updates:
1. Changing library calls
before
```python
from ragas.metrics import InstanceRubricsScore
...
scorer =  InstanceRubricsScore(llm=evaluator_llm)
```
after
```python
from ragas.metrics import InstanceRubrics
...
scorer =  InstanceRubrics(llm=evaluator_llm)
```
2. Sample define
before
```
SingleTurnSample(
```
after
```
sample = SingleTurnSample(
```
> Docs improvements

- src/ragas/metrics/_answer_relevance.py
**Description**: This update refactors the _ascore method to use asyncio.gather for parallel execution of question generation tasks. Key improvements include:
**Issue** : When ResponseRelevancy evaluation loops based on the strictness variable (default 3), which is taking longer than expected
**Performance Enhancement**: By processing all tasks concurrently, the overall execution time is significantly reduced, especially for high strictness values.
**Code Simplification**: The refactored code is more concise and aligns better with Python's asynchronous programming patterns.
**Scalability**: The new implementation handles a larger number of tasks without blocking, making it more suitable for use cases requiring high concurrency.
**Backward Compatibility**: All existing functionality …
> Improve question generation efficiency In Response Relevancy metrics

- pyproject.toml
- src/ragas/metrics/_answer_correctness.py
- src/ragas/metrics/_bleu_score.py
- src/ragas/metrics/_factual_correctness.py
- src/ragas/metrics/_faithfulness.py
- src/ragas/metrics/_noise_sensitivity.py
- src/ragas/metrics/base.py
- src/ragas/prompt/base.py
- src/ragas/prompt/mixin.py
- src/ragas/prompt/pydantic_prompt.py
- src/ragas/utils.py
> fix: remove pysbd and sentence segmenting

- .readthedocs.yml
- src/ragas/dataset_schema.py
- src/ragas/evaluation.py
- src/ragas/metrics/_domain_specific_rubrics.py
- src/ragas/metrics/base.py
> feat: added option to provide experiment_name to evaluate()

- src/ragas/prompt/pydantic_prompt.py
After adapting files to Portuguese and saving.
When recovering, exceptions like these are common due to Portuguese symbols.
Fixing by changing to utf-8 standard
save (c:\Users\jmess\miniconda3\envs\rag\Lib\site-packages\ragas\prompt\pydantic_prompt.py:333)
save_prompts (c:\Users\jmess\miniconda3\envs\rag\Lib\site-packages\ragas\prompt\mixin.py:97)
<module> (d:\GitHub\rag_eval\Untitled-1.py:82)
_run_code (c:\Users\jmess\miniconda3\envs\rag\Lib\runpy.py:88)
_run_module_as_main (Current frame) (c:\Users\jmess\miniconda3\envs\rag\Lib\runpy.py:198)
[Chained Exc: 'charmap' codec can't decode byte 0x81 in position 470: character maps to <undefined>] <module> (d:\GitHub\rag_eval\Untitled-1.py:77)
[Chained Exc: 'charmap' codec can't decode byte 0x81 in position 470: character maps to <undefined>] …
> Change save and load encode to utf-8

- src/ragas/metrics/_factual_correctness.py
#1796 TypeError(ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe'') will trigger when evaluating by `FactualCorrectness`
> fix numpy invert error in metrics

- src/ragas/metrics/_factual_correctness.py
- src/ragas/testset/synthesizers/multi_hop/base.py
- src/ragas/testset/synthesizers/single_hop/base.py
#1796 Compatibility is being fixed due to different sample trigger points
> fix tp&fp calc error

- docs/concepts/metrics/available_metrics/answer_relevance.md
small, but helps with copy/paste 😝
> docs: be consistent with the variable naming of `evaluator_embeddings`

- src/ragas/metrics/_bleu_score.py
The original BLEU score fails for answers shorter than four tokens because the number of 4-grams is zero. Adding the use_effective_order parameter allows users to obtain scores by considering only n-grams up to the number of tokens in the answer when ( N < 4 ). This feature is already implemented in sacreBLEU, so we only need to add the parameter to the BLEU object in ragas. The default is set to False to maintain previous behavior.
> Add optional use_effective_order parameter to BLEU score

- docs/concepts/metrics/available_metrics/context_precision.md
- src/ragas/testset/synthesizers/multi_hop/base.py
- src/ragas/testset/synthesizers/single_hop/base.py
Updated the documentation for NonLLMContextPrecisionWithReference to clarify that it uses non-LLM-based similarity measures, correcting the misleading reference to LLMs.
fixes #1861
> docs: fix incorrect reference to LLM in NonLLMContextPrecisionWithReference metric

- src/ragas/prompt/pydantic_prompt.py
> fix: output parser bug

- src/ragas/run_config.py
fix a minor mismatch of the default value in the docstring
> docs: match default `timeout` in `RunConfig`

- docs/howtos/customizations/metrics/_metrics_language_adaptation.md
- src/ragas/prompt/mixin.py
This pull request includes several changes to the `PromptMixin` class in the `src/ragas/prompt/mixin.py` file. The changes focus on adding a `name` attribute to the class and using this attribute when saving and loading prompts. This solves the error when saving and loading several prompts of different Synthesizers (e.g. MultiHopAbstractQuerySynthesizer, MultiHopSpecificQuerySynthesizer, SingleHopSpecificQuerySynthesizer etc.) as they had the same path associated:
```
themes_personas_matching_prompt_english -> single_hop_specifc_query_synthesizer_themes_personas_matching_prompt_english
query_answer_generation_prompt_english -> single_hop_specifc_query_synthesizer_query_answer_generation_prompt_english
```
* Added a `name` attribute to the `PromptMixin` class.
* Modified the `save_prompts` …
> fix(prompt/mixin): Add name property and add it to saving/loading path.

- src/ragas/dataset_schema.py
- tests/unit/test_dataset_schema.py
This PR addresses a failing test case caused by changes introduced in PR #1879, which modified the error message format. The test has been updated to reflect the new error message, ensuring it passes successfully.
> Fix Broken Test Case Due to Changed Error Message

- src/ragas/prompt/pydantic_prompt.py
The error described in [this comment](https://github.com/explodinggradients/ragas/issues/1688#issuecomment-2602152041) is not resolved when computing Faithfulness.
After digging in judge LLMs responses, there is a JSON parse error happening when parsing the output of the judge. For instance, it happens for the below answer:
```
{
"statements": [
{
"statement": "The Norwegian Dawn cruise ship was denied access to Mauritius.",
"reason": "The context explicitly states that local authorities denied permission for the Norwegian Dawn ship to access the Mauritius capital of Port Louis.",
"verdict": 1
},
{
"statement": "The denial of access was due to potential health risks.",
"reason": "The context directly mentions that the ship was denied access \"citing \\\"potential health risks.\\\"\"", …
```
> Faithfulness prompt update to avoid having single quotes in response

- src/ragas/llms/base.py
This modification allows ragas to handle generations from WatsonX.ai models. The change simply adds the token "eos_token" to the is_finished function.
> added the end of sequence token for the WatsonX family of models

- docs/concepts/metrics/available_metrics/noise_sensitivity.md
- docs/concepts/metrics/available_metrics/traditional.md
- src/ragas/evaluation.py
- src/ragas/metrics/_noise_sensitivity.py
- src/ragas/metrics/_rouge_score.py
- src/ragas/metrics/base.py
- src/ragas/sdk.py
> Metric with different parameter gives different score

- src/ragas/metrics/_faithfulness.py
> Updated the instruction of `StatementGeneratorPrompt` in faithfulness

- src/ragas/metrics/_simple_criteria.py
- src/ragas/sdk.py
The issue arises because `self.single_turn_prompt.instruction` and `self.multi_turn_prompt.instruction` were not being properly assigned during the initialization of `SimpleCriteriaScore()`.
> Fixed simple criteria metric

- src/ragas/testset/synthesizers/single_hop/base.py
This bug probably raise a KeyError since `personas` is not set.
This could be a bug due to an oversight.
Related to #1917
> fix SingleHopQuerySynthesizer::prepare_combinations()

- docs/concepts/metrics/available_metrics/semantic_similarity.md
This PR updates the documentation to correctly describe the Semantic similarity.
The documentation previously stated that a **cross-encoder** was used for computing the semantic similarity score. However, after reviewing the implementation, it is clear that the current approach follows a **bi-encoder** strategy:
- The ground truth and response are encoded independently
- Their embeddings are then compared using cosine similarity
A cross-encoder would typically process both texts together in a single forward pass (e.g., concatenating them before encoding), which is not the case in the current implementation.
For example, in the current implementation:
```python
embedding_1 = np.array(await self.embeddings.embed_text(ground_truth))
embedding_2 = np.array(await …
```
> docs: fix semantic similarity description (cross-encoder -> bi-encoder)

- src/ragas/metrics/base.py
Add @t.runtime_checkable to the ModeMetric protocol to allow runtime type checking using isinstance() and issubclass().
> Enable Runtime Checks for ModeMetric Protocol

- src/ragas/testset/graph.py
When saving the knowledge graph, all the fields of each node is no longer stored in the relationships.
This can save a very large amount of hard disk space.
> When saving kg only save the node id in the relationships

- src/ragas/testset/transforms/default.py
The `default_ transforms`  function defined at  `src/ragas/testset/transforms/default.py` has a problem with handling transforms for documents with 101-500 tokens.
The code divides the `transforms` configurations based on the document's token count.  Several transforms are instantiated when the ["101-500" token count bins the first quartile (Q1](https://github.com/explodinggradients/ragas/blob/2bc29a2b8358ddb6b167fdf7ab0518ad9371463c/src/ragas/testset/transforms/default.py#L128), among them the `cosine_sim_builder`.  While `cosine_sim_builder` is correctly **instantiated** (line 139), it's then **not included** in the list of transforms that are actually returned (line 153).
It appears that `cosine_sim_builder` was likely unintentionally omitted from the returned transforms list.  The …
> Update default.py - Missing `cosine_similarity` transform for docs with Token Count 101–500

- src/ragas/exceptions.py
- src/ragas/metrics/_factual_correctness.py
1. I have noticed that if `response.statements` is an empty list, then the output of `verify_claims` function is `array([], dtype=float64)`, which raises a type error when `~` operation is applied to `reference_response` variable. This occurs in a rare case when hypothesis_list is empty (when there are no claims in the response).
2. A small change is the choice of words in `LLMDidNotFinishException`
> Ndarray dtype fix, improve error wording

- src/ragas/metrics/_noise_sensitivity.py
Absence of any of the required inputs **(user_input, response, reference or retrieved_contexts)** in the test sample results in **KeyError**. For example, the absence of **user_input** in the test sample results in the error message **"KeyError: user_input"**.  
The error message **"KeyError: user_input"** is too abstract.  I  included the following lines of code in the **_ascore()** function definition which will display a clear error message in the absence of any of the required inputs. 
```
if "reference" not in row or not row["reference"]:
raise ValueError("reference is missing in the test sample. Please add reference to the test sample.")
if "user_input" not in row or not row["user_input"]:
raise ValueError("user_input is missing in the test sample. Please add user_input to the test …
```
> Detailed  error message for noise sensitivity metric

- src/ragas/metrics/_factual_correctness.py
- Fixes #1961 
This commit fixes an issue where initializing a FactualCorrectness metric had side effects on other metrics created afterward. 
The problem was caused by PydanticPrompt using a class-level examples list shared across all instances.
By explicitly setting 
```py
self.claim_decomposition_prompt.examples = [] 
```
before extending with specific examples, we ensure each FactualCorrectness instance gets its own isolated examples list, preventing cross-contamination with other metrics.
> Fix shared examples bug in FactualCorrectness metric

- src/ragas/prompt/multi_modal_prompt.py
This document outlines the security vulnerabilities identified in the previous implementation of image handling within the `ImageTextPromptValue` class and details the remediation steps taken in the refactored code. The core issues revolved around insufficient input validation and unsafe handling of user-provided strings, leading to Arbitrary File Read (LFI), Server-Side Request Forgery (SSRF), and potential Denial of Service (DoS) vulnerabilities.
1.  **Arbitrary File Read (LFI):**
*   **Via `file://` URL and `urlopen`:** The `is_valid_url` check allowed `file://` schemes if a `netloc` (hostname like `localhost`) was provided. `mimetypes.guess_type` could be tricked by appending an image extension in a URL fragment (e.g., `#fake.jpg`), which `urlopen` ignores when accessing the file …
> Fix: Arbitrary File Read Vulnerability + Feat: Security settings

- experimental/ragas_experimental/simulation.py
User simulator for multi turn evals
```python
from ragas_experimental.simulation import UserSimulator
user_simulator = UserSimulator(
llm=llm,
prompt=prompt,
agent_function=my_agent,
)
conversation_history = user_simulator.run(persona="A Student who is eager to learn and improve their skills.",
behavior="He can be really curious and asks a lot of questions.",
initial_message={"role": "user", "content": "Helloe, I want to learn about the Muhammed ALi"},)
```
> feat: user simulator

- .github/workflows/ci.yaml
- .pre-commit-config.yaml
- Makefile
- add: make cmd to benchmark tests and get the slowest tests.
- refactor: change pre-commit from run-ci to only check format.
- add: python 3.13 to ci
> Add python 3.13 target, refactor on pre-commit and benchmarking tests

- ragas/src/ragas/testset/synthesizers/multi_hop/base.py
- ragas/src/ragas/testset/synthesizers/single_hop/base.py
**Change**
Using Enum.value instead of Enum.name
It seems that value (description) for QueryStyle is more logical than using names. The current name and value are almost identical, but this might change in the future
> fix: enum values instead of names in testset synthesizers

- .github/workflows/ci.yaml
- .readthedocs.yml
- CLAUDE.md
- docs/experimental/core_concepts/experimentation.md
- docs/experimental/index.md
- docs/experimental/tutorials/agent.md
- docs/experimental/tutorials/prompt.md
- docs/experimental/tutorials/workflow.md
- examples/agent_evals/evals.py
- examples/prompt_evals/evals.py
- examples/rag_eval/evals.py
- examples/workflow_eval/evals.py
- ragas/src/ragas/__init__.py
- ragas/src/ragas/experiment.py
- ragas/src/ragas/experimental/__init__.py
- ragas/src/ragas/utils.py
- ragas/tests/experimental/unit/test_datatable.py
- ragas/tests/unit/test_experiment.py
Done
---
Changes
---
1. Moved and renamed the experiment files, relevant imports in examples and docs
2. Expanded ragas current utils.py implementation to support behaviour from experimental utils
3. Added some tests which I deemed useful
> feat: move `experiment` from experimental to ragas main

- docs/getstarted/evals.md
Hi there!
To fix a couple of typos in `docs/getstarted/evals.md`
> Fix a couple of typos in `docs/getstarted/evals.md`

- src/ragas/metrics/_nv_metrics.py
ContextRelevance class uses the same template(template_relevance1) in both retry loop, instead of template_relevance2.
Replaced template_relevance1 in second retry loop with template_relevance2
> Fix repeating template bug in _nv_metrics.py

- src/ragas/testset/synthesizers/single_hop/base.py
- src/ragas/testset/synthesizers/single_hop/specific.py
Minimal correction to Docstrings of testset regarding single hop use cases.
> fix: update docstrings for single-hop use case

- src/ragas/cache.py
- tests/unit/test_cache.py
As per #1915
Args will not contain the `self` argument, it is bound to func in `__self__` so there is no need to try and strip it.
> Fix issue with cache hits

- Makefile
- Docs build is failing
- Fixes docs build and serve
1. `make build-docs`
2. `make serve-docs`
> fix: update make commands to use uv for docs

- src/ragas/testset/synthesizers/multi_hop/abstract.py
- src/ragas/testset/synthesizers/multi_hop/specific.py
- src/ragas/testset/synthesizers/single_hop/specific.py
- tests/unit/test_analytics.py
The current implementations of the synthesizers (in particular, `MultiHopAbstractQuerySynthesizer` and `MultiHopSpecificQuerySynthesizer`) have hard-coded values for the node- and relationship- properties/types they look for when generating scenarios and samples.  This works when using the default knowledge graph transforms, but may cause unexpected behavior (or force users to use the expected hardcoded values when they do not actually correspond to the reality of property lineage) when using customized the knowledge graph transformations.
This PR allows flexibility in defining the node-property, relationship-property, and relationship-type expected by the *QuerySynthesizers, while retaining the current behavior as default
The bulk of this PR is nonbreaking, but there may be a breaking …
> feature!: knowledge graph flexibility

- docs/index.md
This PR fixes a broken link in the FAQ section of the documentation.
- Old link: /howtos/customizations/metrics/tracing/
- New link: https://docs.ragas.io/en/stable/howtos/customizations/metrics/tracing/
Closes #2140
> docs: fix broken link in FAQ (metrics tracing)

- docs/howtos/customizations/cancellation.md
- docs/howtos/customizations/index.md
- mkdocs.yml
- src/ragas/evaluation.py
- src/ragas/executor.py
- src/ragas/integrations/llama_index.py
- src/ragas/optimizers/genetic.py
- src/ragas/testset/synthesizers/generate.py
- tests/unit/test_cancellation.py
- Closes #2103 
- Tasks can now be cancelled
- Executor import updated
- added tests
- added docs for cancellable task
1. `make test` for testing all tests.
2. `uv run pytest tests/unit/test_cancellation.py` to test cancelled task.
> feat: cancellable task

- docs/extra/overrides/main.html
- mkdocs.yml
- Docs preview sometimes shows random images.
- Add og images and metadata
- Page-specific titles, descriptions
- Add db and twitter card tags.
> update: add og images and metadata to docs

- docs/concepts/metrics/overview/index.md
- Fixes #2271
- The Metrics Overview docs currently say:  
> "All LLM based metrics in ragas are inherited from Metric class."  
This is incorrect.  
- Correct inheritance is:  
- LLM-based metrics → `MetricWithLLM`  
- Non-LLM-based metrics → `Metric`  
- Updated `docs/concepts/metrics/overview/index.md`  
- Corrected wording to reflect that **Non-LLM-based metrics** inherit from `Metric`.  
- Ensures consistency between docs and actual implementation.  
- Related issue: #2271  
- Documentation page: [Metrics Overview](https://docs.ragas.io/en/latest/concepts/metrics/overview/#types-of-metrics-in-ragas)  
**Before:**  
> All LLM based metrics in ragas are inherited from Metric class.  
**After:**  
> All Non-LLM-based metrics in ragas are inherited from Metric class.
> Fix docs: correct inheritance class for Non-LLM metrics

- docs/references/executor.md
- src/ragas/async_utils.py
- src/ragas/executor.py
- src/ragas/metrics/base.py
- src/ragas/testset/transforms/base.py
- src/ragas/testset/transforms/engine.py
- src/ragas/utils.py
- tests/unit/test_async_utils.py
- tests/unit/test_engine.py
- tests/unit/test_executor.py
- tests/unit/test_executor_in_jupyter.ipynb
- refactor: move is_event_loop_running and as_completed to async_utils
This helps separate async features from executor and engine modules, and will prevent circular imports in these modules.
- feat: add ProgressBarManager for enhanced progress tracking
Introduces a new ProgressBarManager class to manage progress bars for both batch and non-batch execution. This includes methods for creating single and nested progress bars, as well as updating batch progress bars, improving user experience during long-running tasks.
- feat: refactor async utilities for improved functionality
- Refactored `run` function from repeated async, executor, and engine logic.
- Changed `as_completed` from async to a regular function for better compatibility.
- Added `process_futures` to handle futures with …
> feature: improve async / executor functionality

- src/ragas/metrics/_topic_adherence.py
- Fixes #2255 
- Fix intermittent TypeError when performing bitwise AND operations between
numpy arrays with incompatible dtypes in TopicAdherenceScore metric.
> fix: resolve TypeError in TopicAdherenceScore bitwise operations

- docs/concepts/metrics/available_metrics/agents.md
Description
This update refactors the provided examples incorporating the corresponding async blocks. The changes enable the code to be executed seamlessly without any further modifications.
Key Changes:
Asynchronous Functionality: Wrapped relevant code in an async def function, allowing for proper asynchronous execution. This eliminates any runtime issues associated with unhandled asynchronous operations.
Evaluator LLM Initialization: Clearly demonstrates the creation of the evaluator_llm object using the LangchainLLMWrapper with the ChatOpenAI model set to gpt-4o. This change improves clarity as the setup of the evaluator was previously not self-explanatory.
Code Readability: Improved formatting and organization of import statements for better readability and maintainability.
> docs: agent metrics code examples improvement 

- src/ragas/llms/base.py
- Fixes #1937 and #2110 
- Modified `src/ragas/llms/base.py` to properly define and use `old_temperature`  (see example below)
N/A
N/A
```python
from langchain_openai import ChatOpenAI
from ragas.llms import LangchainLLMWrapper
from ragas import SingleTurnSample
from ragas.metrics import AspectCritic
llm=ChatOpenAI(model="gpt-4o",temperature=0.33)
evaluator_llm = LangchainLLMWrapper(llm)
print('Before call:')
print(f'llm.temperature: {llm.temperature}') # 0.33
print(f'evaluator_llm.langchain_llm.temperature: {evaluator_llm.langchain_llm.temperature}') # 0.33
test_data = {
"user_input": "summarise given text\nThe company reported an 8% rise in Q3 2024, driven by strong performance in the Asian market. Sales in this region have significantly contributed to the overall growth. Analysts …
```
> Ensure old_temperature is set correctly. Fixes #1937 and #2110

- src/ragas/embeddings/base.py
Title:
Fix ambiguous truth value for empty NumPy arrays in HuggingfaceEmbeddings (fixes #2080)
Description:
This PR resolves an issue where HuggingfaceEmbeddings would raise a ValueError when evaluating an empty NumPy array in a boolean context.
Problem:
Directly checking a NumPy array with if array: is ambiguous when the array is empty or multidimensional, leading to errors like:
ValueError: The truth value of an array with more than one element is ambiguous.
This could occur when users try to generate embeddings with empty inputs.
Solution:
Added an explicit check for empty arrays before any boolean evaluation.
Ensures that the embedding function handles empty inputs safely without errors.
Testing:
Verified embeddings for non-empty inputs work as expected.
Confirmed empty inputs no …
> Fix: avoid ambiguous truth value for empty numpy array in HuggingfaceEmbeddings (fixes #2080)
