ragas/metrics/similarity.py

Redo similarity calculation for 2-d matrix.

Fix bert score

---

Makefile
src/ragas/evaluation.py
src/ragas/metrics/base.py
src/ragas/metrics/factual.py
tests/unit/test_metric.py

feat: make `Result` more usefull

---

src/ragas/evaluation.py
src/ragas/metrics/answer_relevance.py
tests/benchmarks/benchmark_eval.py

fix: error in handling device for tensors

---

Makefile
src/ragas/evaluation.py
src/ragas/metrics/answer_relevance.py
src/ragas/metrics/base.py
src/ragas/metrics/context_relevance.py
src/ragas/metrics/critique.py
src/ragas/metrics/faithfulnes.py
src/ragas/validation.py
tests/unit/test_validation.py

added a validation step that checks
- if the columns corresponding to the metrics passed are present
- if the columns used are of the correct datatype

feat: add validation step

---

src/ragas/metrics/answer_relevance.py
src/ragas/metrics/context_relevance.py
src/ragas/metrics/faithfulnes.py
src/ragas/metrics/llms.py

Improvements and bug fixes for metrics
These bugs appeared to cause drift in results from metrics assessments to ragas metrics.  Some improvements
- fixed temperature for self-check
- Improved prompts for context_relevancy
- post-processing changes for answer_relevancy

Bug fixes and improvements 

---

README.md
docs/integrations/langsmith.ipynb
docs/integrations/llamaindex.ipynb
docs/quickstart.ipynb
experiments/assesments/metrics_assesments.ipynb
experiments/baselines/fiqa/dataset-exploration-and-baseline.ipynb
experiments/baselines/fiqa/improving-baselines.ipynb
src/ragas/evaluation.py
src/ragas/metrics/context_relevance.py

Sorry if this PR is completely not needed but my spell checker corrected this as I was trying it out and I believe you meant "relevancy" for the metrics? Please close if not needed.

fix(spelling): relavancy -> relevancy

---

README.md
docs/integrations/langchain.ipynb
docs/metrics.md
docs/quickstart.ipynb
src/ragas/evaluation.py
src/ragas/langchain/__init__.py
src/ragas/langchain/evalchain.py
src/ragas/metrics/__init__.py
src/ragas/metrics/base.py
src/ragas/metrics/context_recall.py
src/ragas/validation.py

Context recall estimation using annotated answers as ground truth
Context recall was a highly requested feature, as it is one of the main pain points where pipeline error occurs in RAG systems
Introduced a simple paradigm similar to faithfulness

Context Recall

---

src/ragas/metrics/context_relevance.py

Limit context relevancy to 1

---

docs/quickstart.ipynb
src/ragas/metrics/context_relevance.py

fix: spelling of context_relevancy

---

docs/integrations/langchain.ipynb

original note book contains `# incorrect answer` on eval_answer.
Considering actual operation, eval_answer must always be correct, and it is strange to put a wrong answer in eval_answer!

update tutorial notebook

---

.gitignore
src/ragas/validation.py
tests/unit/test_validation.py

fixes #119 
added test cases too

Fix/column-map: fix bug in column_map argument of evaluation

---

README.md
docs/metrics.md

Added to the readme which results each metric is calculated from.
Personally, this information can be found by reading deeper, but for those new to ragas, it will make it easier to get started!
If you think it too much, please just close it!
thanks in advance

Update README with explanation of Ragas metrics

---

pyproject.toml
src/ragas/metrics/context_relevance.py
src/ragas/metrics/faithfulnes.py

- Improve faithfulness prompts
- change the sentence tokenizer to a better one to improve context recall and relevancy.

Improve metrics 

---

src/ragas/metrics/answer_relevance.py

add custom embeddings for answer relevance

---

pyproject.toml

fix: remove dependency on protobuff

---

docs/quickstart.ipynb
src/ragas/metrics/llms.py

fixes #114 #126 
Shoutout to @gabriead for helping test this out :)

fix: added support for azure LLM

---

docs/guides/llms.ipynb
docs/guides/quickstart-azure-openai.ipynb
src/ragas/metrics/answer_relevance.py
src/ragas/metrics/critique.py

Added documentation for azure-openai as alternative quickstart
shoutout to @Techneaux for helping test this

docs: azure openai quickstart

---

docs/Testsetgeneration.ipynb
src/ragas/testset/__init__.py
src/ragas/testset/prompts.py
src/ragas/testset/testset_generator.py

Test set generation paradigm

---

src/ragas/metrics/__init__.py
src/ragas/metrics/answer_correctness.py
src/ragas/metrics/answer_similarity.py
src/ragas/metrics/base.py
src/ragas/validation.py

Answer correctness metrics

---

docs/concepts/index.md
docs/howtos/customisations/llms.ipynb
docs/howtos/customisations/quickstart-azure-openai.ipynb

- Core concepts
- Azure Ai notebook

Docs improvements

---

src/ragas/testset/testset_generator.py

testset generation: bug fixes

---

src/ragas/metrics/answer_correctness.py

use llm from baseclass for answer_correctness
fixes #188

fix: use llm from baseclass for metrics

---

src/ragas/metrics/context_precision.py

bugfix: context_precision

---

src/ragas/testset/testset_generator.py

Hi
I totally understand original code is correct.
But I think my suggestion is much easier to understand.
If you feel it is too much, you can ignore

Refactor testset_generator.py for newbies to understand easily

---

src/ragas/metrics/__init__.py
src/ragas/metrics/context_precision.py

fix: make context_relevancy available

---

src/ragas/llms/base.py
src/ragas/metrics/llms/base.py

Hi,
I added support for models on bedrock. Please check the changes. I'll add examples in a different issue to help users who are using AWS. 
Thanks!

feat: add support for llms on AWS Bedrock (#226)

---

docs/howtos/applications/compare_embeddings.md

* Added hint in synthetic data generation docs to point to user data

added hint in synthetcic data generation

---

src/ragas/evaluation.py

* Removed ragas score from Result class

removed ragas score from result object

---

docs/concepts/metrics/semantic_similarity.md

Fixing a small typo in python code example

docs: Import AnswerSimilarity

---

src/ragas/metrics/_context_precision.py

Hello,
Description : This PR modifies the response evaluation in the context_precision.py script. The changes include:
Making the response evaluation case-insensitive: 
- The code now converts each response to lowercase before checking if "yes" is in the response. This ensures that the evaluation is not affected by the case of the response.
- Handling whitespace in responses: The code now strips leading/trailing whitespace from each response before checking if "yes" is in the response. This ensures that the evaluation is not affected by whitespace in the response.

Case-insensitive and whitespace handling for context_precision.

---

docs/howtos/integrations/langchain.ipynb

Closes https://github.com/explodinggradients/ragas/issues/293

fix: broken link to metrics

---

src/ragas/llama_index/evaluation.py
src/ragas/llms/llamaindex.py
src/ragas/testset/testset_generator.py

I added informative message for import errors regarding llama_index, and changed the existing messages to match each other.

import llama_index gracefully, solves #318

---

docs/concepts/metrics/faithfulness.md

`where and where` -> `where and when`

fix: faithfulness.md

---

src/ragas/evaluation.py
src/ragas/validation.py
tests/unit/test_validation.py

* Changed function remap_column_names to use Dataset.rename_columns function for column remapping

fix: Column remap fix for Dataset evaluation

---

src/ragas/metrics/_faithfulness.py

fix wrong number

---

src/ragas/metrics/_answer_similarity.py

add initial embeddings.encode_kwargs

---

requirements/dev.txt
src/ragas/embeddings/__init__.py
src/ragas/embeddings/base.py

* Added new class for FastEmbed Embeddings

added class for FastEmbed

---

src/ragas/evaluation.py

Fix : 
- Added `ground_truths` argument type-hint info in the evaluation function

Fix: Added `ground_truths` arg type-hint info in the eval function

---

docs/getstarted/evaluation.md

I am not sure about how correct is my rephrasing, please advise

Typo and phrasing correction

---

src/ragas/metrics/_answer_relevance.py

fix: answer relevancy parsing

---

src/ragas/metrics/_context_precision.py

fix: CP example

---

docs/howtos/customisations/aws-bedrock.ipynb
docs/howtos/customisations/embeddings.ipynb
docs/howtos/customisations/llms.ipynb

Added doc changes to:
* Customisations - Bring your own LLMs
* Customisations - Use different embedding models
* Customisations - Use Amazon Bedrock
Fixed: #504

added docs for customisation

---

src/ragas/metrics/_answer_relevance.py

fix: reshape matrix

---

src/ragas/testset/docstore.py
src/ragas/testset/evolutions.py
src/ragas/testset/generator.py
src/ragas/testset/prompts.py
tests/benchmarks/benchmark_testsetgen.py
tests/conftest.py
tests/unit/testset_generator/test_docstore.py

- Also fixes nodes ordering issue
WIP

feat: seed questions using keyphrases

---

src/ragas/metrics/_context_precision.py

fix:handle non dict output

---

src/ragas/evaluation.py

fix: wrap langchain embeddings automatically

---

src/ragas/metrics/_answer_correctness.py
src/ragas/metrics/_context_precision.py
src/ragas/metrics/_context_recall.py

fix: handle non dict cases

---

src/ragas/llms/prompt.py
src/ragas/metrics/_answer_correctness.py
src/ragas/metrics/_context_recall.py

fix assertions and quality in prompt adaptation

---

src/ragas/testset/evolutions.py
src/ragas/testset/extractor.py
src/ragas/testset/filters.py

fix: ensure dict type

---

docs/concepts/metrics/answer_correctness.md
docs/concepts/metrics/answer_relevance.md
docs/concepts/metrics/context_entities_recall.md
docs/concepts/metrics/context_precision.md
docs/concepts/metrics/context_recall.md
docs/concepts/metrics/critique.md
docs/concepts/metrics/faithfulness.md
docs/concepts/metrics/semantic_similarity.md

Based on the converstion with @shahules786 on [Discord](https://discord.com/channels/1119637219561451644/1203785313642749972/1213577555979018312). 
The "How is this calculated" dropdown contains very useful information regarding the metrics, but unfortunately it can easily be overlooked. This PR removes the dropdown and instead puts the information in a "Calculation" section below the "Example" section. 
This way it appears both in the navigation and more prominently on the page itself.
___
- Moved the calculation details from dropdowns to dedicated "Calculation" sections for better visibility in the documentation.
- This change affects multiple metric documentation pages: `answer_correctness.md`, `answer_relevance.md`, `context_entities_recall.md`, `context_precision.md`, …

Docs: Created own section for Calculation (instead of Dropdown) 

---

src/ragas/embeddings/base.py
src/ragas/evaluation.py
src/ragas/executor.py
src/ragas/llms/base.py
src/ragas/metrics/base.py
src/ragas/testset/docstore.py
src/ragas/testset/evolutions.py

Minor PR to clean the whole codebase from the well-known gotcha of [mutable default arguments](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments) - which I encourage you guys to be more careful of.

fix(ragas): remove mutable defaults

---

src/ragas/metrics/_faithfulness.py

closes https://github.com/explodinggradients/ragas/issues/736

Correct Faithfulness Verdict Map

---

src/ragas/testset/prompts.py

update context_scoring_prompt to better prompt and provide two extra examples.

updated context_scoring_prompt and provide extra examples.

---

docs/index.md

Noticed this typo and figured I'd offer to fix it

fix: Explanaitions typo on index.md

---

docs/concepts/testset_generation.md

Updates the docs to fix the LLM acronym expansion.

minor: fix llm expansion in docs

---

.github/workflows/issue-manager.yaml

this helps manage and wranggle issues
https://github.com/tiangolo/issue-manager

chore: added issue manager

---

docs/howtos/customisations/gcp-vertexai.ipynb

doc: Updated vertexai python notebook to use langchain wrapper approach for vertex ai

---

src/ragas/metrics/_answer_correctness.py
src/ragas/metrics/_faithfulness.py
src/ragas/metrics/base.py

#947 
There was a bug when using pysdb sentence segmenter with multiple languages other than English, this PR fixes it.

fix: sentence segmenter for multi languages

---

src/ragas/metrics/_answer_correctness.py

answer-correctness : fix edge cases

---

docs/getstarted/ci.md
docs/getstarted/index.md
docs/howtos/applications/add_to_ci.md
docs/howtos/applications/data_preparation.md
docs/howtos/applications/index.md
src/ragas/_analytics.py
src/ragas/evaluation.py
src/ragas/metrics/base.py
tests/conftest.py
tests/e2e/test_amnesty_in_ci.py
tests/unit/test_analytics.py

new feature based on Ragas reproducability
docs: https://ragas--976.org.readthedocs.build/en/976/howtos/applications/add_to_ci.html#

feat: Ragas CI/CD

---

src/ragas/testset/evolutions.py

fix: patch type issue in evolution parsing

---

docs/howtos/customisations/ragas_custom_model.ipynb

docs: update ragas_custom_model.ipynb

---

docs/concepts/testset_generation.md

Not sure what to add, I just fixed a typo I found in the doc.

Update testset_generation.md - fix typo

---

docs/index.md

Added a missing word in the sentence

chore: Fix typo in index.md

---

docs/concepts/metrics/faithfulness.md

This PR enhances the documentation by improving the clarity and structure of the faithfulness explanation. The changes include:
- Reorganizing the content for better flow and readability
- Clarifying the process of determining the faithfulness of generated answers
- Fixing grammatical errors and improving sentence structure

Improve Clarity and Structure of Faithfulness Explanation in Documentation

---

src/ragas/integrations/llama_index.py

Llama Index integration: optional RunConfig for evaluate()

---

src/ragas/_analytics.py
src/ragas/evaluation.py
src/ragas/testset/generator.py
tests/unit/test_analytics.py

adding analytics to track completed functions.This is to measure the errors that are happening with evals and testset generation

feat: added `track_completed` decorator to track completed functions

---

docs/concepts/metrics/context_recall.md
docs/concepts/metrics/context_utilization.md
docs/concepts/metrics/index.md
src/ragas/metrics/_context_precision.py

reference free context precision

Add context utilization

---

docs/concepts/metrics/summarization_score.md

Fixes conciseness score expression in summarization

[DOCS] - Fix summarization score expression

---

docs/concepts/metrics/faithfulness.md
src/ragas/metrics/_faithfulness.py

update documentation for faithfulness with HHEM

---

src/ragas/evaluation.py
src/ragas/metrics/_answer_relevance.py

fix: handle v0.1 dataset

---

src/ragas/evaluation.py
src/ragas/utils.py

fix: v1 to v2 dataset

---

pyproject.toml
requirements/dev.txt
src/experimental/ragas_experimental/testset/relationships/similarity.py

chores: remove fuzzywuzzy

---

docs/howtos/integrations/langfuse.ipynb

Updated the Langfuse cookbook: Edit links and structure

[howtos] update Langfuse cookbook

---

docs/concepts/metrics/answer_relevance.md

Update answer_relevance.md: Minor spell correct

---

docs/getstarted/rag_testset_generation.ipynb
src/ragas/experimental/testset/simulators/abstract_qa.py
src/ragas/experimental/testset/simulators/base.py
src/ragas/experimental/testset/simulators/base_qa.py
src/ragas/experimental/testset/simulators/generate.py
src/ragas/experimental/testset/simulators/specific_qa.py
src/ragas/testset/evolutions.py

an example visualization with langsmith

feat: support for callbacks and traces in testset generation

---

Makefile
docs/references/evaluation.md
docs/references/index.md
docs/references/metrics.md
docs/references/run_config.md
docs/references/testset_generation.md
mkdocs.yml
scripts/gen_ref_pages.py

added auto gen for reference pages plus the  makefile update for the same.
There is some issues as a lot of  pages ( both __init__ and otherwise ) are empty.

docs:Auto Gen of Reference Page

---

src/ragas/metrics/_answer_relevance.py

fix: remove usage of contexts in response relevancy

---

docs/extra/style.css

- Implemented CSS variables for colors to enhance maintainability.
- Updated styles for links, inputs, and markdown for consistency.
- Added custom scrollbar styling.

feat(styles): refactor CSS to use custom variables

---

docs/extra/components/choose_evaluvator_llm.md
docs/getstarted/rag_evaluation.md
docs/getstarted/rag_testset_generation.md
mkdocs.yml

- Replaced LLM selection blocks with `choose_evaluvator_llm.md` snippet.
- Simplifies updates and reuse across documentation.

feat(docs): add support for reusable snippets

---

src/ragas/metrics/_faithfulness.py

fix attribute error in https://github.com/explodinggradients/ragas/issue…](https://github.com/explodinggradients/ragas/issues/1434.

fix attribute error for faithfulness metric

---

README.md

Add `fire` 🔥 to the link and fix internal link in the README

Fix Quickstart link

---

README.md

I've made Open Analytics a little more explicit, easier to read and lawyer-friendly

Rewrite Open Analytics

---

README.md

Made this a lot shorter, easier to read, added emojis where relevant, and accessible for app developers looking at evals for the first time.

Suggestions for Introduction and Key Features

---

README.md
docs/getstarted/rag_evaluation.md

1. Adds a code snippet
2. Adds a preview of the results so that readers have something tangible to expect

Fixes: Quickstart Ragas Metrics

---

docs/howtos/migrations/migrate_from_v01_to_v02.md

fixed typo in "single_turn_ascore," in "Migration from v0.1 to v0.2."

fixed typo in "single_turn_ascore"

---

docs/concepts/metrics/available_metrics/aspect_critic.md
docs/concepts/metrics/available_metrics/general_purpose.md

Update example codes in AspectCritic metrics to resolve "AssertionError: set LLM before use"

update AspectCritic docs examples

---

docs/community/index.md

Updated community blog posts, with adding my latest Ragas v0.2 guide in Japanese :)

Added community blog posts in Japanese

---

src/ragas/metrics/_context_precision.py

Fix: reference key error in LLMContextPrecisionWithoutReference

---

pyproject.toml

fix bad rendering in https://pypi.org/project/ragas/

chores: fix pypi rendering

---

docs/howtos/migrations/migrate_from_v01_to_v02.md

I found the filename was incorrect, and I fixed it.
Please review and merge if everything looks good.
Thank you.

Fix : Filename in the path

---

src/ragas/metrics/base.py

fix: remove abstract class in Metric

---

docs/extra/components/choose_evaluator_llm.md
docs/extra/components/choose_generator_llm.md
docs/howtos/customizations/customize_models.md

Integrates claude-3-5-sonnet-20241022.
https://docs.anthropic.com/en/docs/about-claude/models

docs: add comment for claude-3-5-sonnet-20241022

---

src/ragas/config.py
src/ragas/dataset_schema.py
src/ragas/embeddings/base.py
src/ragas/losses.py
src/ragas/metrics/base.py
src/ragas/optimizers/__init__.py
src/ragas/optimizers/base.py

feat: train your own evaluators

---

src/ragas/testset/synthesizers/multi_hop/abstract.py
src/ragas/testset/synthesizers/multi_hop/specific.py

fixes: https://github.com/explodinggradients/ragas/issues/1718

fix: add missing query qualifier

---

docs/getstarted/rag_testset_generation.md

This PR fixes two docs issues that I ran into while going through this how-to guide.

Fix link to langchain and add pip install 

---

src/ragas/evaluation.py
src/ragas/integrations/llama_index.py
src/ragas/metrics/_context_precision.py
src/ragas/metrics/_context_recall.py
src/ragas/metrics/_faithfulness.py
src/ragas/metrics/_noise_sensitivity.py
src/ragas/metrics/base.py

Remove reproducibility arg in light on alignment feature which better solves the same problem. 
fixes: https://github.com/explodinggradients/ragas/issues/1711

fix: remove reproducibility arg

---

docs/howtos/applications/index.md

Fix grammar and clarity in sentence about ragas in applications

Fix typo in index.md

---

docs/concepts/metrics/available_metrics/faithfulness.md
docs/concepts/metrics/available_metrics/multi_modal_faithfulness.md
docs/concepts/metrics/available_metrics/multi_modal_relevance.md

- Fixes
- #1748
- Changed ragas.database_schema to ragas.dataset_schema

docs: fix incorrect imports

---

docs/howtos/customizations/testgenerator/_language_adaptation.md

docs: update _language_adaptation.md

---

src/ragas/cost.py
src/ragas/integrations/swarm.py
src/ragas/llms/base.py
src/ragas/prompt/pydantic_prompt.py
tests/unit/test_cost.py

I am currently using Ragas with Bedrock and had to create new token usage parsers. This PR responds to [Issue-1151](https://github.com/explodinggradients/ragas/issues/1151)
Thanks for this package it's nice 😄

Add token parser for Bedrock & fix anthropic typo

---

README.md
docs/getstarted/evals.md
docs/index.md

fixed empty app.ragas.io link in evals.md and Readme.md

docs: updated broken links in ReadMe and evaluation documentation

---

src/ragas/dataset_schema.py

Changed the validate_samples functionality to also tell which indexed sample is causing the issue. #1875

Change the validate_samples functionality

---

README.md
docs/extra/overrides/main.html
mkdocs.yml

adding the message in readme and doc site

docs: added office hour links

---

src/ragas/sdk.py

Add raw request/response logging with RAGAS_ENABLE_HTTP_LOG env flag

feat: add http request-response logging with env flag control

---

src/ragas/metrics/__init__.py
src/ragas/metrics/_answer_accuracy.py
src/ragas/metrics/_nv_metrics.py
src/ragas/sdk.py

first iteration of Nvidia accuracy metric
Added a simple implementation for single turn accuracy, context_relevance and answer_groundedness metrics

nvidia end-2-end accuracy, relevance and groundedness metrics

---

src/ragas/metrics/_noise_sensitivity.py

- the current code was logging a name and mode of  noise sensitivity metric instead of just the name

unnecessary Noise Sensitivity name update

---

src/ragas/evaluation.py

- Improvements in the clarity of the evaluation function documentation
- Grammar corrections

Evaluation function documentation improvements

---

src/ragas/dataset_schema.py

- Fixes: #1995 
The current `validate_user_input` method has a strict validation rule that requires each `ToolMessage` to be immediately preceded by an `AIMessage` with `tool_calls`. This prevents valid conversation patterns where:
1. Multiple `ToolMessage` instances appear in sequence
2. `ToolMessage` instances appear after `ToolMessage` types as long as an `AIMessage` appeared earlier in the conversation
This PR modifies the validation logic to:
1. Track whether we've seen an `AIMessage` at any point in the conversation
2. Allow a `ToolMessage` to follow either an `AIMessage` or another `ToolMessage`
The provided sample demonstrates this pattern with:
```python
from ragas.dataset_schema import MultiTurnSample
from ragas.messages import HumanMessage, AIMessage, ToolMessage, ToolCall …
```

Enhance MultiTurnSample Validator to Support Multiple Tool Calls

---

README.md

Small PR - Commit 7fd54732bb9faf85083ca48da1d7092ebd15a2b5 moved the `_analytics.py`. This PR adjusts sources to changes.

Update analytics source

---

experimental/ragas_experimental/metric/base.py
experimental/ragas_experimental/metric/decorator.py
experimental/ragas_experimental/metric/discrete.py
experimental/ragas_experimental/metric/numeric.py
experimental/ragas_experimental/metric/ranking.py
experimental/ragas_experimental/metric/result.py

-  llm based metric
```py
test_metric = DiscreteMetric(
name="test_metric",
prompt = "Is the {response} a good response to the query {query}?",
values=["pass", "fail"],
)
```
- Writing custom metric logic
```py
@numeric_metric(
name="test_metric",
range=(0, 1),
)
def test_metric(
query: str,
response: str,
) -> MetricResult:
"""
Is the response a good response to the query?
"""
result = 0
return MetricResult(result=result, reason="")
```

feat: llm as prompt as optional

---

.github/workflows/claude-code-review.yml
.github/workflows/claude.yml

changed review to only be triggered for `/claude-review`

chore: only review for `/claude-review` command

---

.cursor/rules/project-structure.mdc
CLAUDE.md
DEVELOPMENT.md
README.md
docs/INSTALL
mkdocs.yml
scripts/dev_docs.sh

- final path fixes for dir migration.

fix: ragas dir structure path fixes

---

.github/workflows/ci.yaml
CLAUDE.md
DEVELOPMENT.md
Makefile
examples/benchmark_llm/evals.py
examples/gdrive_append_example.py
pyproject.toml

- Fixes #2185 
- OR describe the issue: What problem does this solve? How can it be replicated?
- 
- 
- 
1. 
2. 
3. 
- Related issues: 
- Documentation: 
- External references: 
---

Add support for make install-minimal to speed up CI + dev

---

DEVELOPMENT.md
docs/getstarted/install.md

- Removing remnants of `cd ragas`

chore: cleanup docs for ragas directory

---

SECURITY.md

- stop supporting v0.2 security releases
- add support for v0.3.x security releases.

security: stop supporting v0.2 security releases

---

docs/experimental/howtos/index.md
docs/howtos/applications/benchmark_llm.md
docs/howtos/customizations/iterate_prompt.md
mkdocs.yml

- Fixes #[issue_number]
- OR describe the issue: What problem does this solve? How can it be replicated?
- 
- 
- 
1. 
2. 
3. 
- Related issues: 
- Documentation: 
- External references: 
---

Move howtos

---

docs/extra/components/choose_evaluator_llm.md
docs/extra/components/choose_generator_llm.md
docs/getstarted/rag_eval.md
docs/howtos/applications/compare_embeddings.md
docs/howtos/applications/singlehop_testset_gen.md
docs/howtos/customizations/testgenerator/_language_adaptation.md
docs/howtos/customizations/testgenerator/_testgen-custom-single-hop.md
docs/howtos/customizations/testgenerator/_testgen-customisation.md
docs/howtos/customizations/testgenerator/language_adaptation.ipynb
docs/howtos/customizations/testgenerator/testgen-custom-single-hop.ipynb
docs/howtos/customizations/testgenerator/testgen-customisation.ipynb
docs/howtos/integrations/langchain.md
docs/howtos/observability.md
examples/gdrive_backend_example.py
examples/iterate_prompt/evals.py
examples/iterate_prompt/run_prompt.py
examples/ragas_examples/__init__.py
examples/ragas_examples/agent_evals/evals.py
examples/ragas_examples/benchmark_llm/evals.py
examples/ragas_examples/prompt_evals/evals.py
examples/ragas_examples/rag_eval/evals.py
examples/ragas_examples/workflow_eval/evals.py
src/ragas/embeddings/__init__.py
src/ragas/embeddings/base.py

Add deprecation warnings for embeddings

Add deprecation warnings for embeddings

---

docs/extra/overrides/main.html
mkdocs.yml

removed some meta properties to test

---

src/ragas/cost.py
tests/unit/test_cost.py

fixed formatting issues from #1946

OpenAI model cost

---

src/ragas/testset/transforms/splitters/headline.py

Tokens counting

---

docs/concepts/metrics/available_metrics/context_precision.md
docs/concepts/metrics/available_metrics/context_recall.md
src/ragas/dataset_schema.py
src/ragas/metrics/__init__.py
src/ragas/metrics/_context_precision.py
src/ragas/metrics/_context_recall.py

Devpod cn/main

---

src/ragas/prompt/pydantic_prompt.py

- Fixes #2324 
- IndexError in generate_multiple when LLM returns fewer generations than requested

fix: concurrent ResponseRelevancy

---

src/ragas/metrics/base.py
src/ragas/metrics/decorator.py
src/ragas/metrics/discrete.py
src/ragas/metrics/numeric.py
src/ragas/metrics/ranking.py
src/ragas/metrics/validators.py
tests/unit/test_simple_llm_metric_persistence.py

refactor: docs and warnings for metric base new structure
